### ISSUE TITLE
EMD datasets load incorrectly into HDF5 or h5py

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1808] opened 2019-03-07 21:29 UTC
**Describe the bug**
The EMD files written by tomviz can not be opened by HDF5view or h5py. They do load properly back into tomviz though. My guess is that the images are being written in Fortran ordering but h5py/HDF5 expects C-ordering. Im not sure if I can get HDF5 or h5py to understand the Fortran ordering to test this.

**To Reproduce**
1. Load the example reconstruction
2. Save as EMD file.
3. Load into HDFview and view as image or load into h5py and view as an image. Here is an example image from h5py:
![figure_1](https://user-images.githubusercontent.com/15657108/53990240-af53d380-40dc-11e9-8534-4d521f24f688.png)

**Expected behavior**
The data should be loaded and look normal as expected.

**Desktop (please complete the following information):**
 - Windows 10, Dell XPS 13
 - Tomviz version: 1.5.1

**Comment by cryos** [comment] 2019-03-08 17:30
We have code in our [Python Docker logic](https://github.com/cjh1/tomviz/blob/future/tomviz/python/tomviz/executor.py#L368) that is attempting to do this right, but it looks like maybe we are still missing something from the looks of your screenshot. Is there a Python sample to reproduce how you read/displayed this? It looks like maybe matplotlib is displaying a slice of the data?

**Comment by psavery** [comment] 2019-03-08 20:06
It looks like there is an attempt to write to row-major order [here](https://github.com/OpenChemistry/tomviz/blob/master/tomviz/EmdFormat.cxx#L283), but I guess something is missing...

Let us know, @ercius, if you have a Python sample to reproduce your image above.

**Comment by psavery** [comment] 2019-03-09 23:34
FYI, I think I figured out how to view the EMD file (see an example below), and I think the problem here is related to the discussion in #1812 in that the data needs to be transposed rather than just the axes re-ordered. I'll try to find a straightforward way to transpose vtkImageData.

```
import h5py
from matplotlib import pyplot as plt

f = h5py.File('file.emd', 'r')

emdgrp = f['/data/tomography']
data = emdgrp['data'][:]

slice = data[130] # Pick a slice to view

plt.imshow(slice)
plt.show()
``

**Comment by ercius** [comment] 2019-03-10 02:18
Yes. This is a good set of command to read in the EMD file using h5py. You can also use ncempy (pip install ncempy) to read the EMD file without having to know what is in it:
```python
>> import ncempy.io as nio
>> import matplotlib.pyplot as plt
>> emd0 = nio.emd.fileEMD('filename.emd')
>> data, dims = emd0.get_emdgroup(emd0.list_emds[0])
>> plt.imshow(data[130,:,:])
```
I also used h5py manually as @psavery wrote above. I also used the [official HDFview program](https://www.hdfgroup.org/downloads/hdfview/) and got the same result.

If you transpose a numpy array only using `np.transpose()` then you can end up with a **view** into the array with the transposed indices. Checking the flags variable on an array will tell you what the ordering is. You have to use `np.ascontiguousarray()` to actually change the array ordering.

**Comment by psavery** [comment] 2019-03-10 14:54
@ercius The EMD writer/reader is written in C++, so we unfortunately don't have access to the numpy functions in this case.

**Comment by cryos** [comment] 2019-03-10 18:45
@psavery I have some loops in C++ that will do this, let's take a look on Monday. We had meant to loop back and do some more validation as there were some questions on whether we had it totally tied up. Thanks for the example code!

**Comment by cryos** [comment] 2019-03-11 14:26
As I noted in the pull request, the bad thing is that any old EMD file will not load correctly (unless it is square). I wonder if we might want to offer some of the reordering in an operator to aid in further wrangling data. As noted I think image stacks need special treatment.

**Comment by cryos** [comment] 2019-03-11 16:53
I think we should add a TomvizEMD version, it can just be an attribute starting out at 0, every time we change the writer in any way that might have repercussions we can increment it going forward. Unfortunately it does not help with files written by Tomviz 1.5.1 and earlier.

**Comment by ercius** [comment] 2019-03-14 21:50
Anything works for me as long as the EMD file can be read outside of tomviz and the images look right. Thanks for working on this!

**Comment by cryos** [comment] 2019-03-15 18:23
We have tested this with matplotlib, things look right now, and everything is merged. The nightly binaries contain the fix, I would really appreciate that things look good before we close this issue @ercius. Thanks for reporting this, and helping identify the issue.

**Comment by ercius** [comment] 2019-03-16 03:13
Awesome. I'll grab a nightly soon and check it out. Thanks!

**Comment by ercius** [comment] 2019-03-21 21:24
I checked the nightly today (1.5.1-134). The EMD files look good to me. Thanks for fixing this!

**Comment by psavery** [comment] 2019-03-21 21:28
Glad it works! Thanks for checking, @ercius

**Comment by cryos** [comment] 2019-03-22 14:17
I am glad we could get this worked out, sorry it took so long to get it right.

**Closed by cryos** 2019-03-22 14:17 UTC
Labels: bug
