### ISSUE TITLE
Retina display (Mac) not supported; looks pixelated

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#19] opened 2015-05-01 21:17 UTC
GUI and icons look pixelated due to lack of retna display support. This may be resolvable with QT5 implementation.

**Comment by Hovden** [comment] 2015-12-04 20:34
@cryos has mentioned a desire to start building with QT5, so I'm marking as 0.8.

**Comment by mathturtle** [comment] 2016-03-30 20:32
Can someone test this with the new nightly binaries?  We are on Qt 5.6 now, but I don't have a retina display to test with.  Is there some Qt config thing we need to enable or should this just work?  @Hovden @cryos @cquammen

**Comment by cryos** [comment] 2016-03-31 03:01
Moving to Qt 5.6 is the first step, we need 2x versions of all icon assets, this is for Tomviz and ParaView icon assets. I think there were some code updates, I can go back to what we did in another project, but until the 2x icons are available the code changes will not do much. Google Qt 5 retinal display - their docs are pretty good.

**Comment by Hovden** [comment] 2016-06-15 22:23
I think there is a Qt config that needs to be set. The jump to high DPI monitors should be noticeable on most of the application (text etc.) even if the icons are not at 2x.

http://doc.qt.io/qt-5/highdpi.html

**Comment by Hovden** [comment] 2016-07-10 19:25
Any luck with setting QT_AUTO_SCREEN_SCALE_FACTOR to "1" ?

**Comment by cquammen** [comment] 2016-07-20 21:51
I didn't have luck with `QT_AUTO_SCREEN_SCALE_FACTOR `, but did have some success augmenting the `Info.plist` file with the following keys and values:

    <key>NSPrincipalClass</key>
    <string>NSApplication</string>
    <key>NSHighResolutionCapable</key>
    <string>True</string>

One must force the OS to update its cache of the `Info.plist` file by renaming the tomviz application in the Finder to something else, then naming it back to tomviz. This had me stuck for a little while. The good news is that the high-resolution option makes the UI elements render crisply. The bad news is that the VTK rendering only occurs in the bottom left quadrant of the VTK widgets:

![image](https://cloud.githubusercontent.com/assets/360056/17004203/f8f52910-4ea1-11e6-8790-c7bddc560c05.png)

More work will need to be done to expand the rendering to the full window. I don't have a good feel for how long this will take.

**Comment by Hovden** [comment] 2016-07-20 22:08
@utkarshayachit @cryos Has anyone got this to work in Paraview?

**Comment by cquammen** [comment] 2016-07-21 01:18
Not fully. See, for example, http://www.paraview.org/Bug/view.php?id=15826

**Comment by Hovden** [comment] 2016-07-21 01:52
It looks like point 1 and 2 have been addressed.
Quote from your link:
"
Here is what need to be done:
1. NSHighResolutionCapable set to true needs to be added to app's bundle Info.plist file
2. ParaView needs to be build with Qt5, which provides complete support for Retina
3. Several views need to take into account running on HiDPI display, eg. render view which has wrong dimensions when running on NSHighResolutionCapable (see attached screenshot).
"

**Comment by mathturtle** [comment] 2016-07-21 13:54
> It looks like point 1 and 2 have been addressed.

In tomviz yes.  The problem is that ParaView still uses Qt4 by default and they probably won't get around to fixing point 3 until they move to Qt5.  I don't know what the timeline is for ParaView fixing this and moving to Qt5.

**Comment by cquammen** [comment] 2016-07-21 14:02
ParaView 5.2 should come out sometime in late October/early November, but I'm not sure if we are switching to Qt 5 for that release. @utkarshayachit ? It may be possible to make changes that work with both Qt 4 and 5.

**Comment by Hovden** [comment] 2016-12-09 13:45
Any updates on this now that Paraview 5.2 is out?

**Comment by cryos** [comment] 2016-12-09 18:59
The 3D rendering widget will now render into a widget of the correct size, but mouse event coordinates are buggy. Once this is resolved we should be able to enable retina in the application on the Mac.

**Comment by cryos** [comment] 2017-01-30 16:09
This has been a longstanding issue, I have https://github.com/cryos/tomviz/commit/8075d32c88653e8ae8d3fa0312f00fc936a9b61f which changes Tomviz to use retinal display, but https://gitlab.kitware.com/vtk/vtk/merge_requests/2434 is needed in VTK, and https://gitlab.kitware.com/paraview/paraview/merge_requests/1322 is needed in ParaView. I am working with @utkarshayachit on getting them ready to be merged, and they will hopefully be in soon. I want to tag our release soon, and was thinking of pushing this to the next release to give some time for testing.

**Comment by cryos** [comment] 2017-01-31 15:32
So we have merged the VTK and ParaView patches, I just bumped our ParaView and will keep an eye on the build. I am tempted to turn this on, and see what the binaries look like. I would still like to tag a release today/tomorrow so that wouldn't leave a lot of time for testing - thought @Hovden? I intend to make another release at the end of February/early March.

**Comment by Hovden** [comment] 2017-01-31 15:49
I can do some quick testing Wednesday night / tomorrow morning. We could tag tomorrow afternoon.

**Comment by cryos** [comment] 2017-01-31 17:02
I tested the binary that was just uploaded and it looks very good on the whole, interaction worked well. The font in the chart is very small, but I think workable and we can look at DPI awareness or workarounds. The rendering is looking great, comparing pre and post retina the retina looks better and works well. So I would use that even with some of the imperfections, we can get feedback, and always make another point release if bigger issues are discovered.

I used a retinal display iMac to do the testing, and was able to compare the before and after.

**Comment by yijiang1** [comment] 2017-01-31 17:24
@Hovden Here is a screen shot:
<img width="600" alt="screen shot 2017-01-31 at 12 13 41 pm" src="https://cloud.githubusercontent.com/assets/13088588/22476093/1e432892-e7af-11e6-87d8-cb38c0252bc5.png">

**Comment by yijiang1** [comment] 2017-01-31 17:32
Find a bug: when I use the two manual alignment and simple back projection (C++), the main window goes black.
<img width="1280" alt="screen shot 2017-01-31 at 12 30 45 pm" src="https://cloud.githubusercontent.com/assets/13088588/22476643/228df1d2-e7b1-11e6-8f28-f82dc9e474e1.png">

**Comment by cryos** [comment] 2017-01-31 18:05
I missed a few places where we use QVTKWidget. I will submit a pull request migrating them over to the new QVTKOpenGLWidget. I should have a patch soon, and am able to reproduce this locally. Thanks for the report!

**Comment by Hovden** [comment] 2017-01-31 18:34
Thanks for testing @yijiang1 . Assuming the bugs are patched, the retna makes a substantial difference on the mac.

I was surprised to see how much more space efficient and modern the histogram now looks.

Many icons are still low res, but I imagine that is easier to address. I would like to replace a few icons anyways.

**Comment by cryos** [comment] 2017-01-31 19:48
I pushed #848, but it appears to be revealing a new bug I hadn't observed before - upon closing these dialogs everything goes black and the OpenGL widgets fail to render.

**Comment by yijiang1** [comment] 2017-01-31 20:51
There is still a minor issue
On Mac, if I close the alignment ui by clicking <img width="22" alt="screen shot 2017-01-31 at 3 39 30 pm" src="https://cloud.githubusercontent.com/assets/13088588/22483763/967862e2-e7cc-11e6-87a1-3b71eb4ddbd8.png">, a black square will appear
<img width="300" alt="screen shot 2017-01-31 at 3 42 12 pm" src="https://cloud.githubusercontent.com/assets/13088588/22483828/deb92172-e7cc-11e6-9d6b-d1974609b569.png">

**Comment by cryos** [comment] 2017-01-31 20:55
Yeah, I think this is how it looks on the Mac and what I was referring to above. Upon closing the dialogs the main render widgets are getting corrupted, looking into it.

**Comment by cryos** [comment] 2017-01-31 21:22
Think I found a fix, but it will need a VTK, ParaView, Tomviz superbuild update unfortunately.

**Comment by cryos** [comment] 2017-02-01 20:40
So I got the change in VTK, but they did some upgrades on the dashboards, and the ParaView change bring the VTK change is held up in testing right now. It is fixed in my testing, but I need to do some verification on Windows and macOS once I have new binaries.

**Comment by Hovden** [comment] 2017-02-01 22:59
I'm getting an error on OSX when running the "manual tilt axis alignment" (just launch it and close it).
<img width="644" alt="screen shot 2017-02-01 at 5 58 18 pm" src="https://cloud.githubusercontent.com/assets/6197997/22530104/274138ea-e8a8-11e6-9e78-fdcb9b4e1b38.png">

**Comment by cryos** [comment] 2017-02-02 15:41
Yes - this is the fix I was referring to in VTK, once it is in I need to push our ParaView SHA forward, and it should be resolved on all platforms.

**Comment by cryos** [comment] 2017-02-02 19:24
So this seems to work well, unfortunately the machine ran out of disk space, breaking the automatic upload of the installer. iMac with retinal display and regular Mac both looked good, just taking a look on Windows. Linux saw the same issue, and that is where I resolved the bug. So we are in pretty good shape I think.

**Comment by Hovden** [comment] 2017-02-02 22:09
I haven't crashed the latest build. @yijiang1 does it work well for you?

**Comment by yijiang1** [comment] 2017-02-02 22:25
I haven't encountered any new problem related to retina display, though I can easily crash tomviz in other ways.

**Comment by cryos** [comment] 2017-02-02 23:27
I am going to mark this as resolved. If we ever want to make a release we have to draw a line somewhere. Create issues for the ones that you can offer a recipe to reproduce, and we will see what we can do. I am marking this as resolved, Steve is coming up with more icons, but they will take time. I will be tagging the release soon, we will fix as much as we can for the next release in about a month's time.

**Closed by cryos** 2017-02-02 23:27 UTC
Labels: ux

**Comment by Hovden** [comment] 2017-02-03 02:40
Great. I agree. Things look good for a release.

I would like to discuss icons with you before Steve invests too much time. Maybe we can chat briefly tomorrow.
