### ISSUE TITLE
Numpy file cant be written to EMD

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1859] opened 2019-05-15 21:15 UTC
**Describe the bug**
In the course of testing behavior for #1858 I tried to convert a npy file to an EMD file to see if the data was the issue for the crash. I am able to load and view a NPY file, but if I try to save it as an EMD file then the EMD file only has the /data/tomography/ group and it is populated with the proper dim vectors. There is not dataset though.

**To Reproduce**
1. Create a numpy file
```python
import numpy as np
np.save('output.npy',np.ones((10,10,10)))
```
2. Load the npy file into tomviz
3. Select File --> Save data
4. Save the data as an EMD file
5. The EMD file can not be loaded into tomviz. Essentially nothing happens.
6. Check the EMD file structure:
![image](https://user-images.githubusercontent.com/15657108/57809988-9f2f2480-771b-11e9-8e2d-a79413575750.png)

**Expected behavior**
The data should be saved as an EMD file and be able to be loaded into tomviz. Also, it would be good to throw a error or notification if tomviz does not find a dataset in an EMD.

**Desktop (please complete the following information):**
 - Operating system: Windows 10
 - Tomviz version: 1.6.0

**Hardware (please complete the following information):**
 - Device: Dell XPS 13
 - Graphics card: Intel

**Additional context**

**Comment by psavery** [comment] 2019-05-16 13:25
This problem might be specific to Windows. I can't immediately reproduce it on Linux. I'll give it a try on Windows also.

**Comment by psavery** [comment] 2019-05-16 17:04
Unfortunately, I was unable to reproduce the issue on my Windows computer. I used the MSI downloader for Tomviz 1.6.0.
![emd](https://user-images.githubusercontent.com/9558430/57872905-cc8ed780-77da-11e9-94a3-f2aee2086b05.PNG)

My computer is a Windows 10 Lenovo ideapad 700-15ISK.

**Comment by ercius** [comment] 2019-05-18 18:49
Strange. I'll have to double check this. I'll get back to you.

**Comment by cryos** [comment] 2019-06-05 16:09
Let's make sure we resolve this for the next release.

**Comment by cryos** [comment] 2019-07-19 19:02
In my testing this works too, closing for now. Please reopen if this still causes issues on the latest builds.

**Closed by cryos** 2019-07-19 19:02 UTC
Labels: bug
