### ISSUE TITLE
Export Transparent Background Not Working

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#1345] opened 2017-11-13 21:58 UTC
Unable to export transparent background from tomviz.

File "Export Screenshot ..." 

Select Override Color Pallate > Transparent

Exported image has opaque background.

OSX v1.2.0

**Comment by mathturtle** [comment] 2017-11-14 19:42
I can confirm this is broken.  Working on a fix.

**Comment by cryos** [comment] 2017-11-14 20:25
Why did it break? Is this just changes in the underlying ParaView/VTK code?

**Comment by mathturtle** [comment] 2017-11-14 20:28
Yes.  ParaView used to have the transparency option in their settings.  Now they have it in their save screenshot dialog too and they set the option every time.  So my solution of setting it and then calling the ParaView code was breaking since their code sets it now and it defaults to non-transparent, overriding my setting.

**Comment by cryos** [comment] 2017-11-15 18:12
This should be resolved in the latest nightly builds.

**Closed by cryos** 2017-11-15 18:12 UTC
Labels: bug
