### ISSUE TITLE
Code crashing in Ubuntu 16.04

### ISSUE THREAD

**Issue by venkat-purdue** [OpenChemistry/tomviz#1303] opened 2017-10-19 14:55 UTC
I downloaded the latest binary for Linux. When I attempt to run the code (using gdb), it crashes with the following error: 

Reading symbols from ./tomviz...(no debugging symbols found)...done.
(gdb) run
Starting program: Tomviz-1.1.0-Linux-64bit/bin/tomviz 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffd71f5700 (LWP 10650)]
[New Thread 0x7fffce9f0700 (LWP 10651)]

Thread 1 "tomviz" received signal SIGABRT, Aborted.
0x00007fffe1e21428 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.

**Comment by mathturtle** [comment] 2017-10-19 15:08
I can't reproduce this on my Ubuntu 16.04 laptop, but it is possible that I have some dependency installed that you are missing (the main problem with a developer testing on their local machine with dev tools installed).  Can you run ldd ./tomviz and see if any of the libraries are listed as 'not found'?

**Comment by venkat-purdue** [comment] 2017-10-19 15:24
Unfortunately, I do not see any 'not found' in the list of 182 items.  This error is perhaps as you have hypothesized. https://stackoverflow.com/questions/13152775/debugging-c-nptl-sysdeps-unix-sysv-linux-raise-c-no-such-file-or-directo

**Comment by mathturtle** [comment] 2017-10-19 15:28
Ok, it is a real assertion failure then.  I was hoping it was a missing library/packaging problem.  Can you include the backtrace from gdb?  That may give me a hint of which assertion is failing... but we may end up needing a debug build.

**Comment by venkat-purdue** [comment] 2017-10-19 15:50
(gdb) bt
#0  0x00007fffe1e21428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007fffe1e2302a in __GI_abort () at abort.c:89
#2  0x00007ffff19c079c in vtkXOpenGLRenderWindow::CreateAWindow() () from Tomviz-1.1.0-Linux-64bit/bin/../lib/libvtkRenderingOpenGL2.so.1
#3  0x00007ffff1944425 in vtkOpenGLRenderWindow::CreateHardwareOffScreenWindow(int, int) ()
   from Tomviz-1.1.0-Linux-64bit/bin/../lib/libvtkRenderingOpenGL2.so.1
#4  0x00007ffff19c0b6e in vtkXOpenGLRenderWindow::CreateOffScreenWindow(int, int) ()
   from Tomviz-1.1.0-Linux-64bit/bin/../lib/libvtkRenderingOpenGL2.so.1
#5  0x00007ffff19424cd in vtkOpenGLRenderWindow::SupportsOpenGL() () from Tomviz-1.1.0-Linux-64bit/bin/../lib/libvtkRenderingOpenGL2.so.1
#6  0x00007ffff54f63a4 in vtkPVRenderingCapabilitiesInformation::GetLocalCapabilities() ()
   from Tomviz-1.1.0-Linux-64bit/bin/../lib/libvtkPVClientServerCoreRendering.so.1
#7  0x00007ffff54f63e9 in vtkPVRenderingCapabilitiesInformation::CopyFromObject(vtkObject*) ()
   from Tomviz-1.1.0-Linux-64bit/bin/../lib/libvtkPVClientServerCoreRendering.so.1
#8  0x00007fffea5aaba3 in vtkPVSessionCore::GatherInformationInternal(vtkPVInformation*, unsigned int) ()
   from Tomviz-1.1.0-Linux-64bit/bin/../lib/libvtkPVServerImplementationCore.so.1
#9  0x00007fffea5aad42 in vtkPVSessionCore::GatherInformation(unsigned int, vtkPVInformation*, unsigned int) ()
   from Tomviz-1.1.0-Linux-64bit/bin/../lib/libvtkPVServerImplementationCore.so.1
#10 0x00007ffff75652f3 in pqDefaultViewBehavior::onServerCreation(pqServer*) ()
   from Tomviz-1.1.0-Linux-64bit/bin/../lib/libvtkpqApplicationComponents.so.1
#11 0x00007fffe280f876 in QMetaObject::activate(QObject*, int, int, void**) () from Tomviz-1.1.0-Linux-64bit/bin/../lib/libQt5Core.so.5
#12 0x00007ffff6a26f72 in pqServerManagerModel::serverAdded(pqServer*) () from Tomviz-1.1.0-Linux-64bit/bin/../lib/libvtkpqCore.so.1
#13 0x00007ffff69f1f02 in pqServerManagerModel::onConnectionCreated(long long) ()
   from Tomviz-1.1.0-Linux-64bit/bin/../lib/libvtkpqCore.so.1
#14 0x00007fffe280f876 in QMetaObject::activate(QObject*, int, int, void**) () from Tomviz-1.1.0-Linux-64bit/bin/../lib/libQt5Core.so.5
#15 0x00007ffff6a28212 in pqServerManagerObserver::connectionCreated(long long) ()
   from Tomviz-1.1.0-Linux-64bit/bin/../lib/libvtkpqCore.so.1
#16 0x00007ffff6a28599 in pqServerManagerObserver::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) ()
   from Tomviz-1.1.0-Linux-64bit/bin/../lib/libvtkpqCore.so.1
#17 0x00007fffe280f876 in QMetaObject::activate(QObject*, int, int, void**) () from Tomviz-1.1.0-Linux-64bit/bin/../lib/libQt5Core.so.5
#18 0x00007ffff4079787 in vtkQtConnection::EmitExecute(vtkObject*, unsigned long, void*, void*, vtkCommand*) ()
   from Tomviz-1.1.0-Linux-64bit/bin/../lib/libvtkGUISupportQt.so.1
#19 0x00007ffff406905c in vtkQtConnection::DoCallback(vtkObject*, unsigned long, void*, void*) ()
   from Tomviz-1.1.0-Linux-64bit/bin/../lib/libvtkGUISupportQt.so.1
#20 0x00007fffe41fadf9 in vtkCallbackCommand::Execute(vtkObject*, unsigned long, void*) ()
   from Tomviz-1.1.0-Linux-64bit/bin/../lib/libvtkCommonCore.so.1
#21 0x00007fffe4312e72 in vtkSubjectHelper::InvokeEvent(unsigned long, void*, vtkObject*) ()
   from Tomviz-1.1.0-Linux-64bit/bin/../lib/libvtkCommonCore.so.1
#22 0x00007fffea2b7710 in vtkProcessModule::RegisterSession(vtkSession*) ()
   from Tomviz-1.1.0-Linux-64bit/bin/../lib/libvtkPVClientServerCoreCore.so.1
#23 0x00007fffeadafeb3 in vtkSMSession::ConnectToSelf() () from Tomviz-1.1.0-Linux-64bit/bin/../lib/libvtkPVServerManagerCore.so.1
#24 0x00007ffff69b0def in pqObjectBuilder::createServer(pqServerResource const&) ()
   from Tomviz-1.1.0-Linux-64bit/bin/../lib/libvtkpqCore.so.1
---Type <return> to continue, or q <return> to quit---
#25 0x00007ffff752bf8a in pqAlwaysConnectedBehavior::serverCheck() ()
   from Tomviz-1.1.0-Linux-64bit/bin/../lib/libvtkpqApplicationComponents.so.1
#26 0x00007ffff752c0d2 in pqAlwaysConnectedBehavior::pqAlwaysConnectedBehavior(QObject*) ()
   from Tomviz-1.1.0-Linux-64bit/bin/../lib/libvtkpqApplicationComponents.so.1
#27 0x00000000004b66ec in tomviz::Behaviors::Behaviors(QMainWindow*) ()
#28 0x000000000049bc4c in tomviz::MainWindow::MainWindow(QWidget*, QFlags<Qt::WindowType>) ()
#29 0x000000000048e1df in main ()

**Comment by cryos** [comment] 2017-11-01 16:50
I do quite a bit of development on an Ubuntu 16.04 laptop, with an Intel card. Tomviz works well there, either self-compiled or using the binaries we generate.

**Comment by cryos** [comment] 2017-11-21 19:10
Closing, Tomviz needs graphics card drivers that support OpenGL 3.2 or greater.

**Closed by cryos** 2017-11-21 19:10 UTC
