### ISSUE TITLE
Restoring state file forgets view direction and zoom

### ISSUE THREAD

**Issue by ElliotPadgett** [OpenChemistry/tomviz#732] opened 2016-11-02 21:38 UTC
The state file should remember the view direction and zoom for a visualization.  Right now, it resets to the default direction and zoom when a state file is loaded.

**Comment by cquammen** [comment] 2016-11-04 13:56
I tracked this down to the view being reset when deserializing the animation cues. Looking into a solution now.

**Comment by cryos** [comment] 2016-11-10 15:22
Any progress on this?

**Comment by cquammen** [comment] 2016-11-10 15:32
Haven't solved it yet.

**Comment by cquammen** [comment] 2016-11-10 15:33
Loading the animation cues is what resets the view. I have attempted to store the camera settings from the state file and reapply them after the animation cues have been loaded, but the view is still being reset by something.

**Comment by cquammen** [comment] 2016-11-21 16:13
This is also a problem in ParaView if animation scenes are defined. If they are not, then the view direction is preserved in the state file.

**Comment by cquammen** [comment] 2016-11-23 18:22
ParaView's behavior is arguably not a bug. If camera keyframes are defined, the camera will be updated whenever the time is updated, and the time is updated when the state file is loaded. This seems like reasonable behavior within ParaView.

In Tomviz, we should be able to restore the view point from the state file after the camera keyframes have been loaded. The main challenge is to find the right call site for resetting the view point.

**Comment by cryos** [comment] 2016-11-23 18:50
As a user they both appear to be bugs to me, but Tomviz is the one where I am most motivated to see this fixed, having an animation or not seems somewhat orthogonal to restoring the last active view point. I would like to get this fixed in Tomviz before our next release, totally agree that finding a reasonable call site once the animation frames have been loaded should work for us.

**Comment by ercius** [comment] 2016-11-23 19:21
I agree with @cryos. This is very important for sharing data with collaborators.

As a work around can you remove the automatically generated camera orbit in the animations panel? I just tested the following:
1) Load a test data set
2) Move the camera view
3) Save a state file
4) Remove the camera entry in the animations panel
5) Save a state file
The state file in (3) will reset the camera view at the very end of the state file load. The state file saved in (5) does not reset the camera view at the very end and shows the last active view point as desired.

The automatically generated camera orbit is not necessary for every data set. Also, if a user saves animations, then the camera angles/positions define what the user wanted to see and the last active view point is less important.

**Comment by cryos** [comment] 2016-11-23 19:23
I was wondering if we could avoid the noise of saving an untouched default animation that no one ever cared about, but it would still be useful to then restore a default animation. If someone actually edited the path we certainly want to restore that, but even then I feel like starting at the last active view point would be ideal.

**Comment by cquammen** [comment] 2016-11-23 19:25
I am working on a patch to tomviz to restore to the last active view, animation present or not.

**Comment by cquammen** [comment] 2016-11-23 22:07
PR #772 should resolve this.

**Comment by cquammen** [comment] 2016-11-28 18:42
Resolved by #772.

**Closed by cquammen** 2016-11-28 18:42 UTC
Labels: bug, ready, reproducibility

**Comment by cryos** [comment] 2016-11-28 18:47
Thanks Cory, I haven't had time to test it yet but appreciate you digging into the issue.
