### ISSUE TITLE
tomviz crashed at last manual alignment step

### ISSUE THREAD

**Issue by tomo-graphy** [OpenChemistry/tomviz#1704] opened 2018-08-31 07:44 UTC
Hi,

I encountered the problem, that tomviz crashes all the time, when I finish the last alignment step in the manual Translational image alignment. When I jump from the `0` slice to the `1` slice of tomviz chrashes without error. Is there a way to solve this problem?

Best regards

**Comment by mathturtle** [comment] 2018-08-31 13:03
Hi,

This has been reported before (#1468, #1300).  The problem is that we (the developers) have not figured out how to reproduce the crash.  We do the same steps here and it is fine.  I've looked at the code (again) and it should correctly wrap the indices.  I have tried to follow these steps and it did not crash for me (using the latest development version which is not very different from 1.4).  What OS are you on and are you able to catch the crash in a debugger?  What version of tomviz are you using?

**Comment by cryos** [comment] 2018-08-31 13:38
@tomo-graphy if you have a data set you can share where this happens, and can let us know the Tomviz version and operating system you are using we can take a look at this. In the latest version you can save the alignments out during manual alignment, and load them back in. They should also be saved in the recovery file, and so upgrading to Tomviz 1.4.0 will help with recovery/saving more regularly too.

**Comment by tomo-graphy** [comment] 2018-09-03 08:11
I´m using the latest version 1.4.0 on Windows 10 Pro. I also upgraded the PC to 32 GB RAM and a Nvidia 1080TI to speed up Tomviz, and for a lot of memory related crashes it helped. Unfortunately I was not able to catch the alignment crash in a debugger.
Currently I´m not allowed to share this particular dataset, but I can share it with you after publication.
For now I exclude the slice from manual alignment and delete the slice before reconstruction.

**Comment by cryos** [comment] 2018-09-03 14:30
So this only happens for one particular slice? How big are the slices, and how many do you have? We can look at creating a similar pipeline, but it may be specific to your data set. If you come across other data sets that also cause the issue that you can share (even privately) that may help us reproduce the issue. Is this a stack of TIFF images, or a multi-page TIFF file? Thank you for reporting the issue.

**Comment by tomo-graphy** [comment] 2018-09-04 07:59
Some Infos of the data set: 
    - multi-page TIFF file
    - 90 slices 
    - range: -90 to 88°
    - 512x512 px, (original set was 2k x 2k, but binned x4 in Gatans Digital Micrograph Software, and saved as multipage TIFF)
   - 16 bit depth
   - 46.571 KB in total

The crash occures only at the switch from slice 89 to 0.

**Comment by alesgenova** [comment] 2018-09-18 17:59
@nramesar do you have a dataset you would be willing to share for which the crash happens consistently?
I would like to fix this bug once and for all, but so far it's been very hard for us to reproduce the issue

**Comment by cryos** [comment] 2018-11-13 16:20
I am going to close this as we cannot reproduce it. If this can be reproduced in Tomviz 1.5.0 or later please reopen or open a new report. It is of course a concern, and we would like to address it but we need to be able to reproduce the crash in order to do so.

**Closed** 2018-12-10 16:50 UTC
