### ISSUE TITLE
Recent issue building ParaView for Tomviz

### ISSUE THREAD

**Issue by apryor6** [OpenChemistry/tomviz#1416] opened 2018-02-15 17:47 UTC
I was able to compile Tomviz from source previously (a few months ago), but after pulling from master I am running into issues with ParaView (specifically errors involving jpeg/vtkjpeg). I pasted the error below -- has anybody seen this before? I'm using Qt 5.9, CMake 3.9, and Python 3.6. I've done separate pulls/submodule updates for ParaView, ITK, and Tomviz  and also tried repeating the build process from scratch within a fresh directory without success.

This issue may be better suited directly with ParaView, but I figured because I am only using ParaView to satisfy the dependency for Tomviz that it was relevant.

> [ 17%] Building CXX object VTK/Filters/Core/CMakeFiles/vtkFiltersCore.dir/vtkContourFilter.cxx.o
> [ 17%] Building CXX object Wrapping/ClientServer/CMakeFiles/vtkCommonDataModelCS.dir/vtkGenericCellIteratorClientServer.cxx.o
> [ 17%] Building CXX object VTK/Imaging/Core/CMakeFiles/vtkImagingCore.dir/vtkImageMagnify.cxx.o
> [ 17%] Building CXX object VTK/IO/Image/CMakeFiles/vtkIOImage.dir/vtkJPEGWriter.cxx.o
> [ 17%] Building CXX object VTK/Wrapping/Python/CMakeFiles/vtkCommonCorePythonD.dir/vtkXMLFileOutputWindowPython.cxx.o
> Scanning dependencies of target vtkIOTRUCHAS
> [ 17%] Building CXX object VTK/IO/TRUCHAS/CMakeFiles/vtkIOTRUCHAS.dir/vtkTRUCHASReader.cxx.o
> In file included from /Users/ajpryor/tomviz-rebuild/paraview/VTK/IO/Image/vtkJPEGReader.cxx:25:
> In file included from /Users/ajpryor/tomviz-rebuild/paraview-build/VTK/ThirdParty/jpeg/vtk_jpeg.h:32:
> /Users/ajpryor/tomviz-rebuild/paraview/VTK/ThirdParty/jpeg/vtkjpeg/jpeglib.h:71:9: error: unknown type name 'JSAMPLE'
> typedef JSAMPLE *JSAMPROW;      /* ptr to one image row of pixel samples. */
>         ^
> /Users/ajpryor/tomviz-rebuild/paraview/VTK/ThirdParty/jpeg/vtkjpeg/jpeglib.h:660:3: error: unknown type name 'JSAMPLE'
>   JSAMPLE *sample_range_limit;  /* table for fast range-limiting */
>   ^
> /Users/ajpryor/tomviz-rebuild/paraview/VTK/IO/Image/vtkJPEGReader.cxx:179:3: error: use of undeclared identifier 'JPEG_LIB_VERSION'; did you mean 'JMSG_VERSION'?
>   jpeg_create_decompress(&cinfo);
>   ^
> /Users/ajpryor/tomviz-rebuild/paraview/VTK/ThirdParty/jpeg/vtkjpeg/jpeglib.h:906:36: note: expanded from macro 'jpeg_create_decompress'
>     jpeg_CreateDecompress((cinfo), JPEG_LIB_VERSION, \
>                                    ^
> /Users/ajpryor/tomviz-rebuild/paraview/VTK/ThirdParty/jpeg/vtkjpeg/jerror.h:139:10: note: 'JMSG_VERSION' declared here
> JMESSAGE(JMSG_VERSION, JVERSION)
>          ^
> /Users/ajpryor/tomviz-rebuild/paraview/VTK/IO/Image/vtkJPEGReader.cxx:261:3: error: use of undeclared identifier 'JPEG_LIB_VERSION'; did you mean 'JMSG_VERSION'?
>   jpeg_create_decompress(&cinfo);
>   ^
> /Users/ajpryor/tomviz-rebuild/paraview/VTK/ThirdParty/jpeg/vtkjpeg/jpeglib.h:906:36: note: expanded from macro 'jpeg_create_decompress'
>     jpeg_CreateDecompress((cinfo), JPEG_LIB_VERSION, \
>                                    ^
> /Users/ajpryor/tomviz-rebuild/paraview/VTK/ThirdParty/jpeg/vtkjpeg/jerror.h:139:10: note: 'JMSG_VERSION' declared here
> JMESSAGE(JMSG_VERSION, JVERSION)
>          ^
> /Users/ajpryor/tomviz-rebuild/paraview/VTK/IO/Image/vtkJPEGReader.cxx:293:34: error: assigning to 'JSAMPROW' (aka 'int *') from incompatible type 'unsigned char *'
>     row_pointers[ui] = tempImage + rowbytes*ui;
>                        ~~~~~~~~~~^~~~~~~~~~~~~
> /Users/ajpryor/tomviz-rebuild/paraview/VTK/IO/Image/vtkJPEGReader.cxx:448:3: error: use of undeclared identifier 'JPEG_LIB_VERSION'; did you mean 'JMSG_VERSION'?
>   jpeg_create_decompress(&cinfo);
>   ^
> /Users/ajpryor/tomviz-rebuild/paraview/VTK/ThirdParty/jpeg/vtkjpeg/jpeglib.h:906:36: note: expanded from macro 'jpeg_create_decompress'
>     jpeg_CreateDecompress((cinfo), JPEG_LIB_VERSION, \
>                                    ^
> /Users/ajpryor/tomviz-rebuild/paraview/VTK/ThirdParty/jpeg/vtkjpeg/jerror.h:139:10: note: 'JMSG_VERSION' declared here
> JMESSAGE(JMSG_VERSION, JVERSION)
>          ^
> [ 17%] Building CXX object VTK/IO/Core/CMakeFiles/vtkIOCore.dir/vtkUTF8TextCodec.cxx.o
> [ 17%] Building CXX object Wrapping/ClientServer/CMakeFiles/vtkCommonDataModelCS.dir/vtkGenericCellTessellatorClientServer.cxx.o
> 6 errors generated.
> make[2]: *** [VTK/IO/Image/CMakeFiles/vtkIOImage.dir/vtkJPEGReader.cxx.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> [ 17%] Building CXX object VTK/Filters/Core/CMakeFiles/vtkFiltersCore.dir/vtkContourGrid.cxx.o
> [ 17%] Linking CXX shared library ../../../lib/libvtkIOEnSight-pv5.4.dylib
> In file included from /Users/ajpryor/tomviz-rebuild/paraview/VTK/IO/Image/vtkJPEGWriter.cxx:27:
> In file included from /Users/ajpryor/tomviz-rebuild/paraview-build/VTK/ThirdParty/jpeg/vtk_jpeg.h:32:
> /Users/ajpryor/tomviz-rebuild/paraview/VTK/ThirdParty/jpeg/vtkjpeg/jpeglib.h:71:9: error: unknown type name 'JSAMPLE'
> typedef JSAMPLE *JSAMPROW;      /* ptr to one image row of pixel samples. */
>         ^
> /Users/ajpryor/tomviz-rebuild/paraview/VTK/ThirdParty/jpeg/vtkjpeg/jpeglib.h:660:3: error: unknown type name 'JSAMPLE'
>   JSAMPLE *sample_range_limit;  /* table for fast range-limiting */
>   ^
> /Users/ajpryor/tomviz-rebuild/paraview/VTK/IO/Image/vtkJPEGWriter.cxx:283:3: error: use of undeclared identifier 'JPEG_LIB_VERSION'; did you mean 'JMSG_VERSION'?
>   jpeg_create_compress(&cinfo);
>   ^
> /Users/ajpryor/tomviz-rebuild/paraview/VTK/ThirdParty/jpeg/vtkjpeg/jpeglib.h:903:34: note: expanded from macro 'jpeg_create_compress'
>     jpeg_CreateCompress((cinfo), JPEG_LIB_VERSION, \
>                                  ^
> /Users/ajpryor/tomviz-rebuild/paraview/VTK/ThirdParty/jpeg/vtkjpeg/jerror.h:139:10: note: 'JMSG_VERSION' declared here
> JMESSAGE(JMSG_VERSION, JVERSION)
>          ^
> [ 17%] Built target vtkIOEnSight
> 3 errors generated.
> make[2]: *** [VTK/IO/Image/CMakeFiles/vtkIOImage.dir/vtkJPEGWriter.cxx.o] Error 1

**Comment by cquammen** [comment] 2018-02-16 01:35
My guess is that you need to run

git submodule update --init --recursive

in your ParaView source directory. Can you try that and build ParaView again? You shouldn't need to clear out the ParaView build directory, just rebuilding should be sufficient.

**Comment by apryor6** [comment] 2018-02-16 02:09
Thanks for the response. `git submodule update --init --recursive` from within the ParaView source directory returned with no output and I receive the same error originally posted when trying to build Tomviz.
I'm using `CMake` 3.9.0. I would be surprised if that was the issue, but at the same time I'm running out of ideas for possible problems

**Comment by mathturtle** [comment] 2018-02-16 14:58
I think I just figured this out... VTK/ParaView recently updated a lot of the bundled thrid party libraries, including libjpeg.  As a part of that work, how some of the third parties were built changed and this looks suspiciously like you are getting a mix of two different versions of libjpeg.  Try deleting $builddir/VTK/ThirdParty, rerun cmake and try the build again.  This should clean out any artifacts from the old version of libjpeg (and any others) that are in your build tree.

**Comment by apryor6** [comment] 2018-02-16 15:37
If I just delete this directory then CMake fails to configure because it isn't found, so I'm assuming you mean to delete it and repull, but I am already working with the latest version of the code (i.e. I am following BUILDING.md within Tomviz and have cloned everything fresh as of this morning). Is it possible the recent updates you are referring to are breaking and I need to rollback one (or more) of the submodules to an older version?
I'm also trying to compile on my Linux box, so if that succeeds it would be fine enough for now

**Comment by mathturtle** [comment] 2018-02-16 15:42
Not in the source tree.  Delete that path in the build tree or delete your build tree and reconfigure ParaView.  It is old files in your build tree that are causing the problem.

**Comment by apryor6** [comment] 2018-02-16 17:17
Gotcha. I recreated the build directory and configured, but the error is still the same. Is it possible Qt links against one of these image libraries as well and that is causing the issue?

**Comment by mathturtle** [comment] 2018-02-16 17:22
Qt does link against these libraries, but in VTK's internal copies we mangle the symbols so they shouldn't conflict.  This error is at compile time and indicates something is probably wrong with the headers being included... but I'm not sure what it might be.

**Comment by cquammen** [comment] 2018-03-30 18:46
I'm running into this on MacOS now with paraview master. Trying to resolve.

**Comment by cquammen** [comment] 2018-03-30 23:26
Ah ha! `VTK/ThirdParty/jpeg/vtkjpeg/jpeglib.h` is including `jconfig.h`, but rather than finding the one in the ParaView build directory, it is finding `/usr/local/include/jconfig.h`. This version does not define `BITS_IN_JSAMPLE`, but that macro is required to ensure `JSAMPLE`'s type is defined.

**Comment by cquammen** [comment] 2018-03-30 23:30
On my system TBB adds `/usr/local/include` to the search path.

**Comment by mathturtle** [comment] 2018-04-02 13:13
Hmmmm.... maybe rename VTK's to `vtkjconfig.h` (probably not, I think we avoid renaming headers within the third party library).  Otherwise we should figure out how to get CMake to put the build directory location first in the include path?

**Comment by cquammen** [comment] 2018-04-02 13:26
>  Otherwise we should figure out how to get CMake to put the build directory location first in the include path?

Yes, that would be a solution. Even better would be to not have `/usr/local/include` in the include path for the core third party libraries when it is not needed. 

I have confirmed that I cannot build VTK master with TBB enabled, either. I'll file a bug in the VTK tracker and link it here.

**Comment by cquammen** [comment] 2018-04-02 13:38
Correction: the build failure is in `vtkIOImage`, not the jpeg library itself.

**Comment by mathturtle** [comment] 2018-04-02 13:45
Yes, `jconfig.h` is needed by the public headers of libjpeg, so anything that depends on vtkjpeg needs it.  That's why I think making CMake do the right thing here will be difficult since the module system will have to somehow treat vtkjpeg as a special 'these headers go first' module.

**Comment by mathturtle** [comment] 2018-04-02 13:46
This also explains why I couldn't reproduce this, since I installed TBB from Intel's download at `~/tools/tbb` instead of `/usr/local`.

**Comment by cquammen** [comment] 2018-04-02 13:57
For reference, it compiled fine before libjpeg was updated a few months ago. I haven't identified what has changed, however.

**Comment by cquammen** [comment] 2018-04-02 13:59
VTK issue here: https://gitlab.kitware.com/vtk/vtk/issues/17276

**Comment by cquammen** [comment] 2018-04-30 13:52
This should be resolved in ParaView's master branch now. Could you give that a try?

**Comment by cryos** [comment] 2018-05-01 15:02
I will probably update our build instructions, but we recently added forks of ParaView/VTK to the organization, and it contains a local cherry-picked commit needed for VTK. In future I intend to move this forward to the development SHA, and will tag what is used in each Tomviz release.

This will hopefully make it easier to get a ParaView version we are working with, and enable us to be more transparent on what version of ParaView/VTK is used in releases. It also offers the flexibility of making bug fix releases that include bug fixes to the underlying ParaView/VTK code where necessary.

**Comment by cquammen** [comment] 2018-05-07 06:30
@apryor6 This is fixed in the versions of ParaView/VTK @cryos mentioned. For reference, known working versions of ParaView and VTK are:

https://github.com/OpenChemistry/ParaView/commit/b9a216aa78b1570bbd6e73133730782f4a6efdae

and

https://github.com/OpenChemistry/VTK/commit/63c6f6fbd3cc9241437141b4ada9a0f1995f9e72

I'll close this issue as I believe it is now resolved. Please re-open if you find that not to be the case.

**Closed by cquammen** 2018-05-07 06:30 UTC
Labels: in progress

**Comment by apryor6** [comment] 2018-05-07 10:13
Thanks very much for spending time on this. I'll check it out soon!
