### ISSUE TITLE
ITK transforms on Windows getting a Python error

### ISSUE THREAD

**Issue by mathturtle** [OpenChemistry/tomviz#1211] opened 2017-07-26 19:59 UTC
@cquammen 

When I try to run an ITK transform with the Windows binary I get this:

```
Problem encountered while running OtsuMultipleThreshold
Traceback (most recent call last):
  File "Otsu Multiple Threshold", line 111, in transform_scalars
  File "Otsu Multiple Threshold", line 44, in transform_scalars
  File "C:\Users\shawn.waldon\Desktop\Tomviz-1.0.1-39-gb03eec2-Windows-64bit\lib\tomviz\site-packages\tomviz\itkutils.py", line 265, in convert_vtk_to_itk_image
    dst_type = vtk_cast_map()[src_type]
KeyError: 10
Failed to execute the script.
```

I loaded in the example visualization, ran a square root an then tried to run OtsuMultipleThreshold.  (I had also tried skipping the square root and got a similar error, but I didn't copy that one.

But I can import ITK, so the packaging is working.

**Comment by cquammen** [comment] 2017-07-26 20:05
Will take a look

**Comment by cquammen** [comment] 2017-07-31 15:15
Something in the wrapping has changed. I am getting the following error from the 1.0.1-53-g53ae2ac nightly Windows download:

```
Problem encountered while running OtsuMultipleThreshold
Traceback (most recent call last):
  File "Otsu Multiple Threshold", line 111, in transform_scalars
  File "Otsu Multiple Threshold", line 44, in transform_scalars
  File "C:\Program Files\tomviz\lib\tomviz\site-packages\tomviz\itkutils.py", line 265, in convert_vtk_to_itk_image
    dst_type = vtk_cast_map()[src_type]
  File "C:\Program Files\tomviz\lib\tomviz\site-packages\tomviz\itkutils.py", line 156, in vtk_cast_map
    if itk.ctype(possible_type) in itk.WrapITKBuildOptions.SCALARS:
  File "C:\Program Files\tomviz\bin\lib\site-packages\itkLazy.py", line 40, in __getattribute__
    value = types.ModuleType.__getattribute__(self, attr)
AttributeError: module 'itk' has no attribute 'WrapITKBuildOptions'
Failed to execute the script.
```

**Comment by mathturtle** [comment] 2017-07-31 18:15
As far as find/grep are concerned, the name `WrapITKBuildOptions` doesn't exist as a filename or in any file in the build or install trees.  And a git grep in the source tree (tag v4.12.0), shows no matches.  Seems like something changed in ITK that we need to respond to.

**Comment by cquammen** [comment] 2017-07-31 18:25
I'll dig into it. `WrapITKBuildOptions` has things like the scalar types provided in the wrapping, which is useful in some of the automatic casting we are doing between VTK and ITK.

**Comment by cquammen** [comment] 2017-07-31 19:44
Ah, here we go. There was a name change:

    commit f86c9bd5bbd5c93e95aed3f0b1598629c30ec554
    Author: Matt McCormick <matt.mccormick@kitware.com>
    Date:   Sun May 21 15:32:20 2017 -0400

    BUG: Rename WrapITKBuildOptionsPython.py to itkBuildOptions.py
    
    This addresses load errors with itk.force_load() failing to find
    WrapITKBuildOptionsPython and makes the module name
    consistent with itkTypes.py, itkExtras.py, itkConfig.py, etc.
    
    WrapITKBuildOptionsConfig.py did not appear to be used as is removed.
    
    Change-Id: I0137dda928e8d4090b3bb85ff04f09aea20a59ce

**Comment by cquammen** [comment] 2017-08-01 15:04
@mathturtle Can you see if https://github.com/OpenChemistry/tomviz/pull/1221 fixes this issue?

**Comment by mathturtle** [comment] 2017-08-01 15:28
Sure.  It may take a bit, I'm not sure how much I'll have to build.

**Comment by cquammen** [comment] 2017-08-01 15:32
You could just swap the `itkutils.py` file in your current build with the one in #1221. Should even need to rebuild.

**Comment by mathturtle** [comment] 2017-08-01 15:34
Ok, I'll try that.

**Comment by mathturtle** [comment] 2017-08-01 16:00
So `itkBuildOptions` imports and works fine (I tested in the Python console).  But then tomviz crashes...

So it gets around the error in this bug report and exposes another one?

**Comment by cquammen** [comment] 2017-08-01 18:09
I think that's progress. Next step is to find why it crashes. These changes worked for me in the nightly download on Windows, so I can't get a stack trace. Is that something you can get?

**Comment by mathturtle** [comment] 2017-08-01 18:56
I'll try.  I think I have to build it locally for that to work, the binary wasn't giving me an option of getting a stack trace.

**Comment by mathturtle** [comment] 2017-08-01 19:12
Now I can't reproduce it either. (Using the `itkutils.py` from master)  Could it have to do with that comment you made about `itk.BuildOptions` vs `itkBuildOptions`?

**Comment by mathturtle** [comment] 2017-08-01 19:15
Answering my own question: it looks like it.  I checked out the branch at the point where I tested it again and was able to reproduce the crash with that version of `itkutils.py`.  So it looks like you fixed it before merging your branch.

**Comment by cquammen** [comment] 2017-08-01 19:18
There still shouldn't have been a crash just because of `itk.BuildOptions`.  Instead, there should have been an exception reported to the output window.

**Comment by mathturtle** [comment] 2017-08-01 20:07
I can't reproduce the crash without that.  Maybe related to the output window change?  Have you tried reproducing the output window bug on Windows?

**Comment by cquammen** [comment] 2017-08-01 20:16
With the updates I made to `itkutils.py` I can reproduce neither a crash nor a hang on Windows.

**Comment by cryos** [comment] 2017-08-02 13:14
We should verify the latest binary works as expected, but if I am reading this right it looks like the Windows issues described here have now been resolved - is that correct?

**Comment by cquammen** [comment] 2017-08-02 13:21
I believe that to be the case.

**Comment by mathturtle** [comment] 2017-08-02 14:07
I just tested the latest binary and ITK transforms are working.

**Comment by cryos** [comment] 2017-08-02 14:13
That is great, closing this issue.

**Closed by cryos** 2017-08-02 14:13 UTC
Labels: blocker, bug, in progress
