### ISSUE TITLE
Python script windows does not close automatically when quiting tomviz (OSX)

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#780] opened 2016-12-02 19:55 UTC
1. Load a data set.
2. Do a python transform.
3. Open the python script window from pipeline.
4. Left-click the main window, then click the red cross button at the top-left corner.
<img width="106" alt="screen shot 2016-12-02 at 2 52 39 pm" src="https://cloud.githubusercontent.com/assets/13088588/20848197/03921ede-b89f-11e6-8163-f458bb0a7a8b.png">

5. tomviz exits but the python script window and output messages window are still open.

**Comment by mathturtle** [comment] 2016-12-08 16:32
This seems to be an OSX issue.  The dialog's parent **is** getting set correctly... and the application is supposed to exit when the last QWindow is closed anyway.  It works fine on my Linux desktop, just not on OSX for some reason.  I'm leaning toward this being a bug in Qt 5.7.

**Comment by mathturtle** [comment] 2016-12-08 20:42
I can't get this to happen in my simple Qt example, so it must be something we do in tomviz...  But I've tested in tomviz to make sure that the dialog's parent is correct and the dialog and window have the same window flags as the dialog and window in my toy example.

This doesn't happen when you leave the dialog on top and click on the X on the main window.  So possibly a side effect of the dialog being sent behind the main window?  But again the simple example doesn't have that behavior.  I have no idea what is going on here.

One way I can make it work is to call `QApplication::instance()->quit()` in the `closeEvent` handler on the `tomviz::MainWindow`.  Or possibly go through the dialogs and close them all from there.

**Comment by mathturtle** [comment] 2016-12-08 20:56
> So possibly a side effect of the dialog being sent behind the main window?

Yes.  A few more tests have shown that if the main window doesn't completely cover the dialog it works correctly.  @yijiang1 Do you see that too?  But my simple Qt example still doesn't reproduce this even with this trick.

**Comment by yijiang1** [comment] 2016-12-08 21:04
> if the main window doesn't completely cover the dialog

Do you mean something like this?
<img width="1280" alt="screen shot 2016-12-08 at 4 01 56 pm" src="https://cloud.githubusercontent.com/assets/13088588/21027634/b3b279fc-bd5f-11e6-8076-f4fe5f8d0699.png">

I still have the same problem in this case.

**Comment by mathturtle** [comment] 2016-12-08 21:06
> Do you mean something like this?

Yes

> I still have the same problem in this case.

Rats.  I thought I'd figured it out.

**Comment by yijiang1** [comment] 2017-02-09 14:18
I no longer have this problem. Seems it's fixed now.

**Comment by cryos** [comment] 2017-02-17 00:06
Closing for now, we can reopen if this happens again - it may have been a Qt bug as we could not see anything in the Tomviz code. Moving to Qt 5.8.0 cleared up a number of issues.

**Closed by cryos** 2017-02-17 00:06 UTC
Labels: bug
