### ISSUE TITLE
File-->recently opened freezes tomviz

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1292] opened 2017-10-14 22:12 UTC
I consistently get tomviz to freeze after a fresh restart of the program and mousing over the Recently Opened menu option. It freezes for 10 - 20 seconds and then shows up correctly.

Windows 10, tomviz 1.1.0

**Comment by mathturtle** [comment] 2017-10-16 19:35
Peter, have you tried the latest nightly?  I'm testing 1.1.0-104 and I can't reproduce this in that version.

Looking through the code, the only potentially expensive thing it is doing is fetching the settings from disk to get the recent files.  Was the computer running other programs that were hitting the disk hard at the time?

**Comment by ercius** [comment] 2017-10-16 19:47
I just tried again with 110-104 and the issue did not happen. I also rechecked 110-102 and its still not happening. This was happening when I was at home yesterday and now Im at work.

I think I know what was happening. I see in my current list of "recently opened" a file from the network ( a work samba file server). This was my first thought yesterday but I did not see this in my file list. Either I missed it in the list (its the last one listed) or the file was removed from the list when it was not found on the network. This is almost definitely the cause though.

Im not sure if the timeout time for checking for network files can be lowered? It was quite a long pause and easy to accidentally trigger.

**Comment by mathturtle** [comment] 2017-10-16 21:00
That sounds like it could be it.  I'm not sure how much we can do to fix this.  According to the docs [1], using the static version of `QFileInfo::exists` is faster than creating the QFileInfo an then calling exists, so I'm updating our code to use that.  But I'm not sure how much that will help with this.


1: http://doc.qt.io/qt-5/qfileinfo.html#exists-1

**Comment by mathturtle** [comment] 2017-10-17 14:50
@ercius I just merged the change I mentioned above, so it should be a bit better.  But I'm not sure there is much we can do about this.  If you have network file systems in your recent files and they are not there, any query about them will take time to timeout...

**Comment by ercius** [comment] 2017-10-17 14:58
Thanks for trying to improve it. I think waiting for the time out is ok.

**Comment by cryos** [comment] 2017-10-17 17:37
One possible alternative is possibly to do the test for whether the file exists at the point of opening the file, rather than the menu. It would show potentially removed files, but would always show the recent files menu instantly. I wonder if this might be a better solution than what we have, I hate seeing everything hang...

**Comment by ercius** [comment] 2017-10-25 20:34
I think this is fixed in 1.2.0. I loaded a dataset from a remote location, tunred off the Wifi and then opened up the recent files menu option. There was no pause and when clicking on the remote dataset I get this expected error:
![image](https://user-images.githubusercontent.com/15657108/32021751-285497b0-b989-11e7-9abf-6b24368a3bb8.png)
That works for me! I think we can close this.

**Comment by mathturtle** [comment] 2017-10-25 20:41
I think @cryos wants me to change it from an error in the log to a message dialog that pops up.  But I think that is all that is left on this issue.

**Comment by mathturtle** [comment] 2017-11-02 19:19
I have a branch (#1321) that changes the error messages to message boxes.  Once that is merged I think we can close this.  It may even be a small enough change to get into v1.2.1, but I'm not sure.

**Closed** 2017-11-03 16:48 UTC
Labels: bug
