### ISSUE TITLE
Visualization render window broken

### ISSUE THREAD

**Issue by ElliotPadgett** [OpenChemistry/tomviz#1183] opened 2017-06-20 15:41 UTC
On several windows version in tomviz 1.0.1 the render window is broken and shown as a black screen when you load sample data (see screenshots).  We have a room of ~15 people on windows computers and about half of them have this problem.

![image](https://user-images.githubusercontent.com/12242066/27341979-d69c84a4-55ac-11e7-9fdb-a025e2448d31.png)

![image](https://user-images.githubusercontent.com/12242066/27342023-efae78a8-55ac-11e7-9b13-d53c9249a2db.png)

**Comment by cryos** [comment] 2017-06-20 15:51
Is this the case with 1.0.0 too, or is this a new regression in the 1.0.1 release? Do you have any further information on the version of Windows, and the graphics cards being used. There have been a number of changes to the render window in the underlying VTK/ParaView codebase since the 1.0.0 release.

**Comment by cryos** [comment] 2017-06-20 15:52
You can view/download previous releases from https://github.com/openchemistry/tomviz/releases

**Comment by ercius** [comment] 2017-06-21 13:33
I can offer my experience with 1.0.1 as I see the exact same thing. I'm
using Windows 10 on my laptop with an Intel graphics driver (Dell XPS 13).
I downgraded to 1.0.0 and everything works perfectly. This is a new
regression.

When Tomviz starts you see the normal background with a black square in the
lower left. If you load a data set then the screen goes completely black.
That describes the screen shots from Elliot.

**Comment by cryos** [comment] 2017-06-21 14:25
Thanks @ercius, this looks like a regression in VTK/ParaView. So far it looks specific to Windows with Intel graphics. If anyone observed this behavior in another combination we would like to know. We will be tracking this, and may look at obtaining additional test machines to cover this increasingly common setup. I have a similar laptop running Linux and it works fine.

**Comment by cryos** [comment] 2017-07-31 14:51
This should be resolved now, it was a bug introduced in ParaView that has since been resolved. I would appreciate you verifying the latest nightly binary no longer displays this behavior if you get a chance.

**Comment by cquammen** [comment] 2017-07-31 15:09
When investigating #1211, I still ran into this when my Intel on-board graphics was used on my Windows machine. This is in the current nightly build (downloaded July 31, 2017), which is 1.0.1-53-g53ae2ac.

**Comment by cryos** [comment] 2017-07-31 15:14
OK thanks, I will bump the PV SHA to the latest RC, it would be good to know if that resolves it once the updated binaries are ready.

**Comment by cquammen** [comment] 2017-07-31 15:18
I will check the new builds tomorrow morning.

**Comment by cryos** [comment] 2017-08-01 15:00
New binaries look like they built, if anyone has any cycles to test them I would really appreciate it.

**Comment by cquammen** [comment] 2017-08-01 15:09
Just tested on Windows with my integrated Intel 4600 chip, and it works as expected. Confirmed that the build from two nights ago fails with the same setup.

**Comment by cryos** [comment] 2017-08-01 15:10
That's great, thanks for verifying @cquammen. Closing this issue, please reopen if you think it may not be resolved on your hardware @ElliotPadgett with the latest nightly.

**Closed by cryos** 2017-08-01 15:10 UTC
Labels: blocker, bug
