### ISSUE TITLE
Panels no longer moveable (or too glitchy to use)

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#351] opened 2016-02-25 14:38 UTC
Once a panel, such as the properties panel, has been popped out as a separate window I cannot figure out how to return it to the main panel. The behavior has changed from previous builds—presumably a qt5 issue.

**Comment by cryos** [comment] 2016-02-25 14:59
This seems to behave as I would expect on Linux, assuming this is Mac, I will take a look there.

**Comment by Hovden** [comment] 2016-02-25 15:00
Ok, I reloaded the app and it is more responsive. Not sure what is going on. I will try and pin down the diagnoses.

**Comment by cryos** [comment] 2016-04-07 19:01
Closing this for now, not able to reproduce. Let's reopen if we can come up with a way to reliably reproduce.

**Closed by cryos** 2016-04-07 19:01 UTC
Labels: bug
