### ISSUE TITLE
Canceling ART causes huge memory increase

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1505] opened 2018-04-19 20:41 UTC
The ART is not canceled properly. It still eats up a huge amount of memory and the memory is still consumed after canceling. Looking at the memory use of ART should be done to see if it can be reduced.

**Comment by cryos** [comment] 2018-04-24 16:14
I let this get to slice 6, and then canceled, tried again at slice 10. That is with the sample tilt series, you can see the memory use (which is pretty high), but it is also returned:
![image](https://user-images.githubusercontent.com/42214/39200058-0c523090-47b9-11e8-9c26-3ef973494b59.png)

**Comment by cryos** [comment] 2018-04-26 18:45
I am going to close this for now as I have been unable to reproduce, like I said we found a number of issues and improved things over the last week. Please reopen if you are seeing this in the latest builds.

**Closed by cryos** 2018-04-26 18:45 UTC
Labels: bug
