### ISSUE TITLE
White Background As Default

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#817] opened 2017-01-12 18:23 UTC
I'd like to suggest a white background as the default. I prefer using a white background as the default for a couple reasons:
(1) It better suits use in a figure for scientific publication (we usually work on white)
(2) The UX looks nicer.
(3) Grey can be a difficult color to reproduce without the hex value.

<img width="1524" alt="screen shot 2017-01-12 at 1 03 57 pm" src="https://cloud.githubusercontent.com/assets/6197997/21901898/c52dc078-d8c7-11e6-94c4-e89f0db41a20.png">
<img width="1524" alt="screen shot 2017-01-12 at 1 04 23 pm" src="https://cloud.githubusercontent.com/assets/6197997/21901901/c7430e2c-d8c7-11e6-96ee-545971d118ad.png">

**Comment by ercius** [comment] 2017-01-12 18:28
I don't like the gray either, but I prefer black rather than white. Volume
visualizations seen to be better visible than on the gray. Ill try white
out to see how it looks though. Ultimately, adding a option to set the
default per user would be best.

Also, I always thought it interesting that data presented at conferences
prepared by Avizo was obvious due to blue default background. It's a subtle
advertisement for Avizo.

**Comment by Hovden** [comment] 2017-01-12 18:32
I use white for manuscripts (and web content), but often use black for presentations. There is a Viz argument for grey (e.g. Maya uses gray as default).

I agree about the advertisement. The biomed community is famous for really nice 3D Viz in their publications and they are most often on white backgrounds. I do think the EM community is advertising for Avizo when they use the blue gradient. It also suggests that people usually just use the default parameters (see also Digital Micrograph plots).

**Comment by ElliotPadgett** [comment] 2017-01-13 19:02
I would also vote for white, since it is most common (universal?) for manuscripts, and at least as common as dark backgrounds for web and presentations.

**Comment by ercius** [comment] 2017-01-13 19:51
I just tested white vs black. I'm a convert to white.

**Comment by cquammen** [comment] 2017-01-19 15:16
Please take a look at the latest master branch. It has a tool bar for picking the default ParaView color palette, a white background color palette, and a black background palette.

![image](https://cloud.githubusercontent.com/assets/360056/22112247/384fa7c0-de30-11e6-902c-f128376f887c.png)

If this is satisfactory, please feel free to close this issue.

**Comment by yijiang1** [comment] 2017-01-19 15:48
1. When first loading tomviz, I still see the old background.
2. Click color palette -> White Background. The background becomes white.
3. Click color palette -> Make Current Palette Default.
4. Click color palette -> Default Background. The background becomes the old one.
Furthermore,
5. Reset tomviz (File->Reset), now I see white background.
6. Click color palette -> Default Background. The background becomes the old one.

It's kind of confusing that the "Default Background" cannot be set by "Make Current Palette Default".

**Comment by cryos** [comment] 2017-01-19 15:49
I didn't think of that, but the naming is confusing. Thanks for the feedback, we should resolve that before closing this issue.

**Comment by cquammen** [comment] 2017-01-19 15:52
> 1. When first loading tomviz, I still see the old background.

We can change that to white easily if that is the consensus, which I think it was.

> 4. Click color palette -> Default Background. The background becomes the old one.
Furthermore,

Ah, I see the confusion. The Default Background really means ParaView's default, but that isn't at all clear. We should probably rename that to Gray Background or something.

> 5. Reset tomviz (File->Reset), now I see white background.

This is expected based on your set of actions.

**Comment by cryos** [comment] 2017-01-19 15:57
#831 changes the name, still not entirely convinced that the print background is what everyone would want, and find it very stark on the screen.

**Comment by yijiang1** [comment] 2017-01-19 16:02
Another thing:
1. Open tomviz.
2. Right-click in the 3D rendering window, then click "Set Background Color" and set background to a different color.
3. Now, the color palette doesn't work any more.

**Comment by cquammen** [comment] 2017-01-19 16:10
For better or worse, this is ParaView's behavior for color palettes. Without going into too much detail, once you pick a custom color for the background, the "background property" becomes unlinked from the color palette color. The assumption is that you really want a specific background color instead of one from the palette, so ParaView does't apply the palette background the next time you choose one.

We don't have to keep that behavior in Tomviz, though.

**Comment by cryos** [comment] 2017-01-19 16:11
Confirmed here, I guess the color palettes do not override the background color setting as I would have expected. Reset will reset it, but that it very disconcerting.

**Comment by cryos** [comment] 2017-01-19 20:35
I think overriding the background color when selecting a palette would make the most sense

**Comment by Hovden** [comment] 2017-02-23 18:20
*bump
Color palette still overrides background color. Approach suggested by @cryos is sensible.

**Comment by cryos** [comment] 2017-02-23 18:33
@cquammen can you add the necessary changes for Tomviz please? To be clear when we choose a new palette that should override any custom background color that might have been chosen previously by our user. So if I choose a green background color, but later pick the black background palette I would like to then see the full palette including the black background.

**Comment by cquammen** [comment] 2017-02-23 18:36
Understood. Yes, will do.

**Closed** 2017-03-02 15:36 UTC
Labels: ux
