### ISSUE TITLE
Manual tilt series alignment not advancing reference image with keyboard a/s

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#891] opened 2017-02-13 19:47 UTC
The manual tilt series alignment widget does not advance the reference image when a/s keyboard shortcuts are pressed. Clicking on the arrows next to the image number has the desired effect though.
![screen shot 2017-02-13 at 11 42 45 am](https://cloud.githubusercontent.com/assets/15657108/22900125/2112d706-f1e2-11e6-97a2-c2697a4ba398.png)

**Comment by yijiang1** [comment] 2017-02-13 19:52
Yo need to click the tilt image on the left first. Same for arrow keys.

**Comment by ercius** [comment] 2017-02-13 19:56
I just double checked that, but no luck. The arrow keys work for shifting but the a/s still does not advance the reference image. I have to click on the Static radio button and then back to Prev. Then it updates.

**Comment by yijiang1** [comment] 2017-02-13 20:02
> I have to click on the Static radio button and then back to Prev.

Yeah you have to do this for changing the REFERENCE image.

The A/S shortcut adjusts the CURRENT image.

**Comment by ercius** [comment] 2017-02-13 22:03
This is not the expected behavior.

What you describe is the expected behaviour when the Static button is selected. Then a/s should only advance the current image.

If the Prev. or Next radio button is selected then the Reference AND Current image should advance by +1 for a and -1 for s. 

Furhter, the behavior is different for clicking the Current image up/down arrows compared to the a/s keyboard shortcuts.

**Comment by yijiang1** [comment] 2017-02-13 22:20
> If the Prev. or Next radio button is selected then the Reference AND Current image should advance by +1 for a and -1 for s.

Yeah this is the feature we need but missing in tomviz currently.

**Comment by ercius** [comment] 2017-02-13 22:32
>Yeah this is the feature we need but missing in tomviz currently.

Im really confused then. What are Prev. and Next radio buttons for then?

**Comment by cryos** [comment] 2017-02-16 20:04
I noticed issues in the interaction, and it did not feel natural to me. It would be good to define what we want, and ensure that the interaction is as expected here. I would have expected what Peter expected, and the way it is written the next and prev buttons do not behave as I would have thought - I would have thought static would do what @yijiang1 is stating.

**Comment by ercius** [comment] 2017-02-25 22:22
Should we define how this should work? @Hovden might have some input here as well. Currently, this GUI is a little difficult to work with during alignment.

**Comment by yijiang1** [comment] 2017-03-02 15:40
bump

**Comment by Hovden** [comment] 2017-03-02 16:48
I agree with this: "If the Prev. or Next radio button is selected then the Reference AND Current image should advance by +1 for a and -1 for s."

@yijiang1 can you change the alignment interface so that when prev or next is selected you are always aligning to adjacent images in the series?

**Comment by yijiang1** [comment] 2017-03-02 16:52
I'm not familiar with this interface but I can take a look.

**Comment by Hovden** [comment] 2017-03-02 16:54
@yijiang1 that's right, I thought you had helped with this.

@cryos might be better suited.

**Comment by cryos** [comment] 2017-03-02 17:00
I will get this fixed up, I think I know where the issue is, and should have something by the end of the day.

**Comment by Hovden** [comment] 2017-03-02 17:27
Great, thanks.

**Comment by ercius** [comment] 2017-03-02 18:50
You need to be careful with how you make this change. If you allow the user to choose the direction AND the Next/Prev button then you can spend an hour manually un-aligning your data by accident.

Lets take a case where you want to start at the middle 0-degree image and align outward from there.

If you set the Prev radio button then the reference image is 0-degree and the align image is +1. If you then press the down arrow (or the 'a' keyboard button) then the reference image is -1-degree and the align image is 0-degree. Any shifts you apply to the 0-degree image now mis-align it with respect to your +1 image. Stepping down like this then has you misalign every image as you go.

This problem is the sameif you start at 0-degree and go the positive direction (press 's') while keeping the "Next" button selected. Non-experts might make such a mistake easily.

The design decision I made in a similar manual alignment GUI I previously built (in IDL) was to not allow the user to select the Next/Previous button. I tied the reference/align image to which direction you were going with respect to the middle. So you always try to align to the 0-degree image, which makes sense because that is your starting field-of-view.

**Comment by cryos** [comment] 2017-03-02 18:57
Sorry I took so long to dig into it, but this should resolve the issue.

**Comment by ercius** [comment] 2017-03-02 19:00
@cryos We should be mindful of how flexible this use interface is according to my edited comment above. I think I got it right this time.

**Comment by cryos** [comment] 2017-03-02 20:07
My change makes the keyboard shortcuts work as the user interface does, and so it is probably a reasonable improvement. I take your point @ercius that we should do a little work to prevent bad situations at either extreme.

**Comment by yijiang1** [comment] 2017-03-02 21:17
> I tied the reference/align image to which direction you were going with respect to the middle. So you always try to align to the 0-degree image, which makes sense because that is your starting field-of-view.

This can be done using the Static radio button right?

**Comment by ercius** [comment] 2017-03-03 01:32
Yes, but that was not what I really meant in the context of using a
non-profit static reference.

I mean you want to align
0 to 1, 1 to 2, 2 to 3...
0 to -1, -1 to -2, -2 to -3...
The 0 image is the global reference.

**Comment by yijiang1** [comment] 2017-03-03 15:13
@ercius 
Following my edited comment above, how about these tweaks?

1. Change the ui a little bit:
![picture1](https://cloud.githubusercontent.com/assets/13088588/23555161/d76fe572-fff5-11e6-8c3d-7325404a536b.png)

The box next to "Reference image" updates whenever the reference image changes and are disabled if prev or next are selected.

2. Always use 0-degree tilt image as the default reference. If there is no 0-degree image, then use the middle image.

**Comment by ercius** [comment] 2017-03-03 18:27
This looks good. I would have to try it to see how it really works. Two quick ocmments:

Can you update the # in the reference and current image boxes, but also keep the reference image from being changed if Prev/Next is selected?  I think you have implemented this after reading your edited comment.

Also, can you swap the positions of the Reference image and Frame rate boxes?

**Comment by cryos** [comment] 2017-03-03 19:12
Checking I am understanding correctly. I think it would look great having reference image immediately below the current image selection. If next/prev are selected then the control for reference could be disabled and the text updated, i.e. if moving to current image of 7, with prev selected the reference would be 6 but still greyed out, only becoming active upon selecting static. If there was a desire, then it would be possible to save/restore the static image number upon choosing that in the radio buttons.

Is that the kind of interaction you envisioned, or something different?

**Comment by yijiang1** [comment] 2017-03-03 19:28
> Is that the kind of interaction you envisioned, or something different?

This is what I'm thinking. I'm working on a branch to implement this. I'll push it shortly.

**Comment by cryos** [comment] 2017-03-03 19:51
Sounds great, I look forward to taking a look.

**Comment by yijiang1** [comment] 2017-03-03 20:28
@ercius How does the UI look in #991 ?

**Comment by Hovden** [comment] 2017-03-07 13:31
Looks great.

**Closed by Hovden** 2017-03-07 13:31 UTC
Labels: bug
