### ISSUE TITLE
Add ITK

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#158] opened 2015-08-13 14:11 UTC

**Comment by mathturtle** [comment] 2015-08-19 18:16
The most recent binaries should have ITK bundled.

**Comment by Hovden** [comment] 2015-08-19 18:17
Great. Can you provide a simple example(s) to demonstrate and get us started with tinkering?

**Comment by cryos** [comment] 2015-08-26 14:42
If you can provide a simple example @mathturtle that would be great, we should also talk to Matt McCormick now that ITK is bundled about some fuller examples.

**Comment by mathturtle** [comment] 2015-08-26 14:44
I'm working on it.  I emailed Matt yesterday afternoon asking what some good filters to demonstrate might be.  We may have to update the bundled ITK though to turn more things on in its build process.

**Comment by cryos** [comment] 2015-08-26 15:00
Sounds like whilst it is packaged there are some teething issues. We will leave it in the binary so that people can experiment but I don't want to delay our bug fix release. I will move this to the 0.7 milestone as a tracker, and we can continue working on some examples.

**Comment by mathturtle** [comment] 2015-09-16 14:43
@Hovden here is a sample ITK script for segmentation that can be used in the tomviz 'custom python transform' dialog.  I don't know much about ITK, so this may not be optimal, but I think it works (as far as I can tell anyways).
```
def transform_scalars(dataset):
    """Define this method for Python operators that 
    transform the input array"""

    from tomviz import utils
    import numpy as np
    import itk

    # Get the current volume as a numpy array.
    array = utils.get_array(dataset)

    # Set up some ITK variables
    itk_image_type = itk.Image.F3
    itk_converter = itk.PyBuffer[itk_image_type]

    # Read the image into ITK
    itk_image = itk_converter.GetImageFromArray(array)

    # ITK filter (I have no idea if this is right)
    filter = itk.ConfidenceConnectedImageFilter[itk_image_type,itk.Image.SS3].New()
    filter.SetInitialNeighborhoodRadius(3)
    filter.SetMultiplier(3)
    filter.SetNumberOfIterations(25)
    filter.SetReplaceValue(255)
    filter.SetSeed((24,65,37))
    filter.SetInput(itk_image)
    filter.Update()


    # Get the image back from ITK
    result = itk.PyBuffer[itk.Image.SS3].GetArrayFromImage(filter.GetOutput())

    # This is where the transformed data is set, it will display in tomviz.
    utils.set_array(dataset, result)
```

**Comment by Hovden** [comment] 2015-09-16 15:07
Thanks. @yijiang1 and I will dig into what ITK can provide for segmentation.

**Comment by yijiang1** [comment] 2015-09-17 19:07
I get a "No module named itk" error when I import itk.

**Comment by mathturtle** [comment] 2015-09-17 19:09
Are you using the binaries or is this a local build?

**Comment by yijiang1** [comment] 2015-09-17 19:16
My local build.

**Comment by cryos** [comment] 2015-09-17 19:25
You would need to build/install locally, this is in the superbuild that packages our dependencies. You should just install the package if it is included, just like SciPy etc. Failing that you could build/install it locally for testing purposes.

**Comment by mathturtle** [comment] 2015-09-17 19:26
Then it is pretty much expected.  I think the simplest way to fix it is to download the binaries the superbuild uses: [OSX](http://www.tomviz.org/files/itk-4.8.0-macosx10.8.tar.gz) [Windows 64bit](http://www.tomviz.org/files/itk-4.8.0-windows-64bit.zip) [Windows 32bit](http://www.tomviz.org/files/itk-4.8.0-windows-32bit.zip).  Unzip/untar the files, then run the following in your terminal to tell python where to find ITK (double check my paths, I'm writing this from memory):

OSX:
```
export DYLD_LIBRARY_PATH=/path/to/extracted/files/lib/itk:$DYLD_LIBRARY_PATH
export PYTHONPATH=/path/to/extracted/files/lib/itk/ITK-4.8/Python:$PYTHONPATH
```
Windows:
```
set PATH=/path/to/extracted/files/bin;%PATH%
set PYTHONPATH=/path/to/extracted/files/bin/Lib/site-packages;%PYTHONPATH%
```

You'll either have to configure the environment variables globally, or run them every time you start a shell that you want to use ITK.

**Comment by yijiang1** [comment] 2015-09-17 19:46
I see. Thanks!

**Comment by yijiang1** [comment] 2015-11-16 04:52
> export DYLD_LIBRARY_PATH=/path/to/extracted/files/lib/itk:$DYLD_LIBRARY_PATH
> export PYTHONPATH=/path/to/extracted/files/lib/itk/ITK-4.8/Python:$PYTHONPATH

What is /path/to/extracted/files/ ?  I can't find a directory ending with  "/ITK-4.8/Python" (on Mac).

**Comment by mathturtle** [comment] 2015-11-16 15:25
Did you download and extract the file I linked to for your OS?  It should be under lib in the directory you extracted it to.

**Comment by yijiang1** [comment] 2015-11-16 18:51
> Did you download and extract the file I linked to for your OS?

@mathturtle Sorry I missed this. I just download the binaries and now I'm able to import itk in Tomviz. Thanks!

**Comment by yijiang1** [comment] 2015-11-16 21:16
I first did this:

> Then it is pretty much expected. I think the simplest way to fix it is to download the binaries the superbuild uses: OSX Windows 64bit Windows 32bit. Unzip/untar the files, then run the following in your terminal to tell python where to find ITK (double check my paths, I'm writing this from memory):
> 
> OSX:
> 
> export DYLD_LIBRARY_PATH=/path/to/extracted/files/lib/itk:$DYLD_LIBRARY_PATH
> export PYTHONPATH=/path/to/extracted/files/lib/itk/ITK-4.8/Python:$PYTHONPATH

Next, to reproduce the crash, 
1. Open Python.
2. Type "import itk"
3. Type any itk code. For example, "itk_image_type = itk.Image.F3" from the example above.
4. Then, python exits immediately and prints out this message in terminal: 
Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6

**Comment by mathturtle** [comment] 2015-11-16 21:24
Strange.  Following those instructions on our OSX machine works fine.

**Comment by yijiang1** [comment] 2015-11-16 21:33
Maybe I did not install ITK properly? Is there other ways to do that?
@Hovden Do you have the same problem?

**Comment by mathturtle** [comment] 2015-11-16 21:35
Well, you could build it yourself... but that takes a long time and we're trying to avoid it.  Do you get the same problem if you run the tomviz binaries and try to run the ITK script?

**Comment by yijiang1** [comment] 2015-11-16 21:43
My Tomviz doesn't crash on binaries but prints out a different error message (when I run the example script above): 

Failed to execute the script.
Traceback (most recent call last):
  File "Transform Data", line 13, in transform_scalars
  File "/Applications/tomviz.app/Contents/Libraries/ITK-4.8/Python/itkLazy.py", line 42, in __getattribute__
    itkBase.LoadModule(module, namespace)
  File "/Applications/tomviz.app/Contents/Libraries/ITK-4.8/Python/itkBase.py", line 108, in LoadModule
    LoadModule(dep, namespace)
  File "/Applications/tomviz.app/Contents/Libraries/ITK-4.8/Python/itkBase.py", line 108, in LoadModule
    LoadModule(dep, namespace)
  File "/Applications/tomviz.app/Contents/Libraries/ITK-4.8/Python/itkBase.py", line 108, in LoadModule
    LoadModule(dep, namespace)
  File "/Applications/tomviz.app/Contents/Libraries/ITK-4.8/Python/itkBase.py", line 108, in LoadModule
    LoadModule(dep, namespace)
  File "/Applications/tomviz.app/Contents/Libraries/ITK-4.8/Python/itkBase.py", line 118, in LoadModule
    module = loader.load(swigModuleName)
  File "/Applications/tomviz.app/Contents/Libraries/ITK-4.8/Python/itkBase.py", line 224, in load
    return imp.load_module(name, fp, pathname, description)
  File "/Applications/tomviz.app/Contents/Libraries/ITK-4.8/Python/ITKCommonPython.py", line 32, in <module>
    _ITKCommonPython = swig_import_helper()
  File "/Applications/tomviz.app/Contents/Libraries/ITK-4.8/Python/ITKCommonPython.py", line 28, in swig_import_helper
    _mod = imp.load_module('_ITKCommonPython', fp, pathname, description)
ImportError: dlopen(/Applications/tomviz.app/Contents/Libraries/ITK-4.8/Python/_ITKCommonPython.so, 2): Library not loaded: @rpath/libITKLabelMap-4.8.1.dylib
  Referenced from: /Applications/tomviz.app/Contents/Libraries/ITK-4.8/Python/_ITKCommonPython.so
  Reason: image not found

**Comment by mathturtle** [comment] 2015-11-16 22:16
On the bright side, I can reproduce that one locally.  I fixed this when we first started working with ITK, but I don't remember what I did and apparently I didn't update my instructions for building ITK to include the solution.  I'm working on it.

**Comment by mathturtle** [comment] 2015-11-18 19:05
I have merged a fix for this into the superbuild OpenChemistry/tomviz-superbuild#67.  New binaries should generated in a few hours.

**Comment by yijiang1** [comment] 2015-11-19 17:31
@mathstuf I can run the example code without any error on latest binaries.
I'm still having trouble using itk on my local build. @Hovden has the same problem as well.

**Comment by mathturtle** [comment] 2015-11-19 18:02
Sorry for the spam Ben :)

Yi: I'm not sure why it is failing for your local builds.  Do you still get that PyThreadState error?  If so then maybe @cryos can give us some input.

**Comment by mathturtle** [comment] 2015-11-19 18:22
Something you might try:
There is a script in the superbuild: https://github.com/OpenChemistry/tomviz-superbuild/blob/master/projects/apple/fixup_itk.py
You could try running it with the location you extracted ITK as its argument.  It doesn't really have much of a command line interface (It is only really intended to be run by the superbuild).  I don't know if it will help, but it might.

**Closed** 2015-11-25 17:24 UTC
Labels: enhancement, in progress
