### ISSUE TITLE
Integrate tiff reader voxel dimensions into data properties panel

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#1068] opened 2017-03-22 13:34 UTC
We discussed integrating the tiff reader voxel dimensions into data properties panel so users aren't inundated with the configure parameters popup every time data is loaded.

**Comment by cryos** [comment] 2017-03-22 14:39
This is a duplicate of #878, there are some updates on the way there.

**Closed by cryos** 2017-03-22 14:39 UTC
Labels: ux
