### ISSUE TITLE
"Mark as tilt series" must be run twice for some datasets to unlock tomography menu

### ISSUE THREAD

**Issue by ElliotPadgett** [OpenChemistry/tomviz#445] opened 2016-06-23 17:25 UTC
After loading a tilt series in tiff format, when I click "Mark as tilt series" and fill in the angle selection popup the angles get populated correctly but the tomography menu options are all greyed out except "Mark as volume" and "Generate tilt series".  I can work around the bug by clicking "Mark as volume" and then "Mark as tilt series" again, which makes the menu options available.

I have reproduced this with two different tiff stacks, but it does not seem to happen with the sample dataset .

**Comment by ElliotPadgett** [comment] 2016-06-23 18:30
@yijiang1 pointed out that this does not always reproduce, so I went and tried to see what conditions cause it and I noticed a few things:
1) Pushing the cancel button on "Mark as tilt series" does not stop it from marking it as tilt series (I can open a separate issue for this.
2) Deleting a dataset or pushing File>Reset with something open may be necessary to trigger the bug.
3) When it works correctly, the dataset gets selected in the "Visualization Modules" list to the left as soon as the "Mark as tilt series" popup appears.  When it does not work, this does not happen and the current visualization module stays selected instead.

**Comment by mathturtle** [comment] 2016-06-23 19:08
I think I have actually seen this once, but I couldn't reproduce it at all so I didn't mention it.  If you've seen it enough to report (and track down conditions to make it happen) then I can start debugging.  Thank you for taking the time to figure out some of what causes this.  Reading your list triggered an idea of what was going on in another issue too.

I can explain 1 from your list above... and probably fix it without too much trouble.  That menu item is doing two things.  First it is marking the data source as a tilt series.  Then it is calling the 'Set Tilt Angles' menu item's callback that displays the dialog.  When the dialog is canceled, it only cancels the 'Set Tilt Angles' part.

**Comment by ercius** [comment] 2016-07-20 18:27
Not sure what the status of this issue is, but the newest binary (0.8.0-151) requires the user to run "mark as tilt series" multiple times to unlock the Tomography menu. This was working correctly in a previous nightly (0.8.0-135) but is now broken again in 0.8.0-151.

**Comment by mathturtle** [comment] 2016-07-20 18:33
I was looking into it earlier and could only reproduce it when I do File->Reset.  I'm still trying to figure out why this happens.  @ercius are you on OSX?  Maybe it happens more there.

**Comment by mathturtle** [comment] 2016-07-20 19:18
Nevermind, I think I finally tracked this down.  There should be new builds with my fix tonight.  @ercius Can you try tomorrow's build?  The fix is in 0.8.0-156-g6bd70ae (so if you have a number > 156 it should be there).

FYI: the 'g6bd70ae' part of the version (from the version I gave above) is actually the most useful thing you can tell me to identify the version you are running.  The other parts of the version are generated to be human readable but I have to convert it back before I can put it into git.  And since most developers only use these hashed values when referring to commits (and some ambiguity problems), git doesn't provide an easy way to convert the human readable part of the version back to the hash.

**Comment by ercius** [comment] 2016-07-21 00:33
@mathturtle 
> Can you try tomorrow's build?

Most definitely.
> FYI: the 'g6bd70ae' part of the version (from the version I gave above) is actually the most useful

Thanks for the info and will do going forward. I should have recognized the second part as a GIT commit hash value.

**Comment by ercius** [comment] 2016-07-21 21:09
@mathturtle I just tried build g4f0edc9. Mark data as tilt series works as expected now. Thanks for fixing!

**Closed** 2016-09-15 19:08 UTC
Labels: bug, in progress
