### ISSUE TITLE
Progress bar stop updating during reconstruction

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#855] opened 2017-02-02 16:23 UTC
Sometimes the progress bar stop updating during reconstruction (especially back projection). 
After reconstruction is done, some dialogs such as set tilt angles become black.

![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/13088588/22557721/5db22420-e939-11e6-8ce1-8cf9d78ab99a.gif)

**Comment by cquammen** [comment] 2017-02-02 16:27
Tangential question: how do you make the animated GIF?

**Comment by yijiang1** [comment] 2017-02-02 16:32
I use QuickTime Player to record a video and then use http://ezgif.com/video-to-gif to convert mp4 to gif.

**Comment by cjh1** [comment] 2017-02-02 16:38
@yijiang1 Can you confirm that the progress.update(...) calls are being make in your python script?

**Comment by yijiang1** [comment] 2017-02-02 16:47
There is a progress.update function? 
I use "self.progress.value = step" to update progress bar.

**Comment by cjh1** [comment] 2017-02-02 16:51
Sorry yes, that is what I meant

**Comment by yijiang1** [comment] 2017-02-02 17:12
The Direct Fourier Method doesn't have this problem. 
Maybe it's caused by calling another function in for-loop?
<img width="463" alt="screen shot 2017-02-02 at 12 01 31 pm" src="https://cloud.githubusercontent.com/assets/13088588/22559651/cc7a253c-e93f-11e6-94e9-654e629f619f.png">
(code in Recon_WBP.py)

**Comment by cjh1** [comment] 2017-02-02 17:38
That is what I am wondering, if you put a print before and after that function call, we can see if it getting stuck there.

**Comment by yijiang1** [comment] 2017-02-02 18:31
I add a print statement before the wbp2 function and the progress bar no longer gets stuck!

**Comment by cjh1** [comment] 2017-02-03 18:06
@yijiang1 I am unable reproduce this issue are there particular parameters you are providing to the transform and which dataset are you using?

**Comment by yijiang1** [comment] 2017-02-03 18:15
I'm using default parameters and the star-shaped sample dataset.

**Comment by cjh1** [comment] 2017-02-03 18:17
And this happens every time for you? ( i am using the same dataset and defaults )

**Comment by yijiang1** [comment] 2017-02-03 18:20
Pretty much, though it gets stuck at different steps.

**Comment by cjh1** [comment] 2017-02-03 18:21
Does it get unstuck?

**Comment by yijiang1** [comment] 2017-02-03 18:22
Nope

**Comment by cryos** [comment] 2017-02-03 18:26
Is this on macOS, Windows, Linux? I know a lot of your recent testing seems to be on macOS where we have seen some update issues. Are using the binaries we generate? If not it may also be worth updating to Qt 5.8.0 as it has quite a few fixes for different platforms (not sure if anything specifically addressing this).

**Comment by cjh1** [comment] 2017-02-03 18:26
but does the reconstruction complete?

**Comment by yijiang1** [comment] 2017-02-03 19:48
> but does the reconstruction complete?

Yes, and after that the ui goes crazy.


> Is this on macOS, Windows, Linux?

It's on macOS

It seems the binaries work fine. I'll update my Qt.

**Comment by cjh1** [comment] 2017-02-03 21:27
Lets close this for now and reopen if you still have problems with latest  Qt

**Closed by cjh1** 2017-02-03 21:27 UTC
Labels: bug

**Comment by yijiang1** [comment] 2017-02-06 21:22
> If not it may also be worth updating to Qt 5.8.0

How can I update my qt to 5.8 (on Mac)?
