### ISSUE TITLE
Histogram Sig Figs

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#543] opened 2016-08-03 00:31 UTC
Can we lower the number of significant digits on the histogram y-axis? Maybe we need only one decimal (X.Y or e.g. 1.0e6) at the most?
![clipboard01](https://cloud.githubusercontent.com/assets/15657108/17349904/a364bada-58d6-11e6-8a39-c1b0e0ee6e19.png)

**Comment by cryos** [comment] 2016-08-07 17:05
I will look into this, it should not be showing that many figures, in fact I set it to show none but it is possible there is a big in the tick generation code on Windows (I am assuming this is Windows - I just checked and don't see this issue on Linux).

**Comment by ercius** [comment] 2016-08-07 19:28
Yes. It's windows 10.

**Comment by cquammen** [comment] 2016-10-03 17:43
Behavior confirmed on Windows 10 with latest nightly build.

**Comment by cryos** [comment] 2016-10-03 17:45
I see this too, and it is a VTK bug in the charting code. It appears the API we are using fails to respect the requested significant figures. This is not intended behavior, we actually tried to make this look simpler/tweak the display of the chart.

**Comment by Hovden** [comment] 2017-03-02 16:29
Is this still an issue? Things look fine on OSX.

**Comment by cryos** [comment] 2017-03-02 16:34
I think it is, I will try and spend a little time on Windows digging into this.

**Comment by Hovden** [comment] 2017-03-02 16:54
Ok. Not a big priority for 1.0

**Comment by ercius** [comment] 2017-03-02 18:34
Its still an issue on 0.9.3-205-g1293187. But yes, low priority.

**Comment by cryos** [comment] 2017-03-27 03:29
Sorry, this won't make 1.0, but I will try and get to this as it is irritating on Windows.

**Comment by ercius** [comment] 2017-03-27 23:57
Thanks for the update. It's only an irritation as you say.

**Comment by cryos** [comment] 2017-12-08 19:52
Closing this issue, using one significant figure due to bug in MSVC, erring on the side of consistency over platforms.

**Closed by cryos** 2017-12-08 19:52 UTC
Labels: in progress, ux
