### ISSUE TITLE
Error when dragging the mouse after a right-click

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz#348] opened 2016-02-12 18:32 UTC
1. Load a dataset.
2. Right-click the background, you should see the "Set Background Color" option.
3. Now left-click the background, and drag it.
4. Then this error message pops up:
 QNSView mouseDragged: Internal mouse button tracking invalid (missing Qt::LeftButton) (:0, )

**Comment by cryos** [comment] 2016-02-12 18:58
Are you on El Capitan? This looks like a Qt bug, many will be addressed in Qt 5.6.0.

**Comment by yijiang1** [comment] 2016-02-12 19:39
Yes I'm on El Capitan.

**Comment by luzpaz** [comment] 2016-02-16 12:11
@cryos where is it indicated that it will be fixed in Qt5.6 ?
(ref: https://bugreports.qt.io/browse/QTBUG-42846)

**Comment by cquammen** [comment] 2016-02-16 15:39
Confirmed that this still exists in Qt 5.6 branch from Qt repo.

Maybe some votes on the issue would help encourage a resolution.

This message should not affect interaction. It would be nice to be able to filter out this message, however.

**Comment by cryos** [comment] 2016-02-19 01:39
@luzpaz you are right, sorry for any confusion. Voted and watched the issue you linked to, this is very unfortunate. We should filter the message to avoid causing concern needlessly, it seems the list of issues with El Capitan and Qt 5 is growing...

**Comment by cryos** [comment] 2016-02-19 01:40
@cquammen can you look into filtering this please, I will assign it to you for now.

**Comment by cquammen** [comment] 2016-02-19 02:05
Sure, I will take a look.

**Comment by cquammen** [comment] 2016-03-24 15:40
This issue does not seem to have any associated usability issues. I have put in a merge request in ParaView to suppress this warning message.

https://gitlab.kitware.com/paraview/paraview/merge_requests/700

**Comment by cquammen** [comment] 2016-03-25 14:06
Unfortunately, the official binary release of Qt 5.5.0 on Mac OS X still reports this warning. The ParaView topic mentioned above will suppress it, though.

**Comment by cquammen** [comment] 2016-03-25 14:32
The ParaView topic that filters out these messages has been merged. This issue will go away when the ParaView version is moved to current master or newer.

**Closed by cquammen** 2016-03-25 14:32 UTC
Labels: bug, in progress
