### ISSUE TITLE
Deleting Volume Module during Reconstruction Causes Crash [MacOS]

### ISSUE THREAD

**Issue by jtschwar** [OpenChemistry/tomviz#1788] opened 2019-01-18 15:53 UTC
**Describe the bug**

If a Volume Module is deleted in the middle of a Live Reconstruction then Tomviz crashes. 

**To Reproduce**
1. Go to Any Dataset
2. Click on Run any Reconstruction (with Live Capability)
3. Select Volume Module during reconstruction, delete and it will crash at the next update.
4. See error:

Segmentation fault: 11

**Expected behavior**

Not to crash.

**Screenshots**

![image](https://user-images.githubusercontent.com/32110921/51397421-30481300-1b0f-11e9-9901-f01fa7de0447.png)

Delete the volume module in the middle of the reconstruction and at the next update, Tomviz will crash. 

**Desktop (please complete the following information):**
 - Operating system: macOS 10.14.2
 - Tomviz version: 1.5.1-41-g516e7464

**Hardware (please complete the following information):**
 - Device: Macbook Pro

**Comment by cryos** [comment] 2019-07-10 17:32
Maybe you can check on this too @cjh1

**Comment by cjh1** [comment] 2019-07-10 17:37
Sure

**Comment by cjh1** [comment] 2019-07-19 18:50
I am unable to recreate this issue. I was able to add and remove the module multiple times without a crash.

OS: macOS 10.12.6
Tomviz: 1.6.0-153-gaa86c427

**Comment by cryos** [comment] 2019-07-22 13:16
Closing as we cannot reproduce the crash. We will keep an eye out, a backtrace or similar would be very helpful if you see this crash and can get one.

**Closed by cryos** 2019-07-22 13:16 UTC
