### ISSUE TITLE
Context menus/keyboard shortcuts in application

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/tomviz#48] opened 2015-05-13 18:04 UTC
Add context menus to the module views, along with keyboard shortcuts that make it easy to delete things from the data transforms, etc.

**Comment by bdalevin** [comment] 2015-06-25 22:11
Having tested out both versions 0.4 and 0.5, I have a couple of specific ideas for this that I believe will increase user friendliness a lot. 

1) In the piplelines sub-window, if you right click on either a data set, or an individual vizualization module within that data set, there should be an option in the context menu that allows the user to delete that specific dataset / module. 

2) When right clicking on a render view window, there should be an option to allow the user to change background colour.

**Comment by cryos** [comment] 2015-06-26 00:40
We will get to one soon, and that is exactly what was planned. I will get back to you on two, we are planning on making this more accessible but do you really want to change your background colour that often? I am starting work on a number of interface improvements.

**Comment by ElliotPadgett** [comment] 2015-06-26 01:24
In typical use I expect it will not need to be changed very often (not more than once a session probably), but it should be easy to find.

**Comment by bdalevin** [comment] 2015-06-26 13:11
Experienced users won't need to change background more than once a session. New users (who, with M&M coming up, are an important target demographic) will want to play around with colour schemes when they first start out. 
Either way, since it's a basic feature, users will expect it to be easy to find. Context menu seems like the best place to find it.

**Comment by ElliotPadgett** [comment] 2015-06-26 15:34
I don't think it would change with experience level.  Any time you change the color map you may also need to change the background, so maybe it would be useful to also have a button to access the background color near the color map controls.

**Comment by bdalevin** [comment] 2015-06-26 15:39
Yeah, that would be a good idea. The choice of background colour and the module colour map are intimately connected, so maybe it makes the most sense to have the controls to change them close together.

**Comment by mathturtle** [comment] 2015-07-15 18:17
Part (1) is addressed by #121 and is a duplicate of issue #14.

**Comment by Hovden** [comment] 2015-07-16 14:30
I think issue this goes a little farther than #14.

For this release I'd say add "clone" to the right click of a module. And, if it is not too much time, right clicking on a render view window to allow the user to change background colour (i.e. access the view properties popup).

Then close this issue.

**Comment by utkarshayachit** [comment] 2015-07-23 14:09
* Add **Clone** to context menu for Data Source
* Right-click on view to edit view properties to change background color.

**Comment by mathturtle** [comment] 2015-07-29 17:56
@Hovden When you get a chance to test out the new build, can you let me know if all these menus work?  If they do, we can close this issue.

**Comment by bdalevin** [comment] 2015-07-29 17:57
Tested. Change background and delete modules from context menu work under
windows.

On 29 July 2015 at 13:56, Shawn Waldon <notifications@github.com> wrote:

> @Hovden <https://github.com/Hovden> When you get a chance to test out the
> new build, can you let me know if all these menus work? If they do, we can
> close this issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenChemistry/tomviz/issues/48#issuecomment-126038467>
> .
>



-- 
Barnaby Levin

 Applied Physics PhD Candidate,
Cornell University
​271 Clark Hall,
 142 Sciences Drive,
Ithaca, NY​
 USA
14853

MPhys, Oxford University

**Comment by Hovden** [comment] 2015-07-29 18:16
Yep. Tested on my Mac and tested on @bdalevin 's Windows.

**Closed** 2015-07-29 18:16 UTC
Labels: under-development, ux
