### ISSUE TITLE
Crashes when rescaling colormap with non-orthogonal slice.

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#127] opened 2015-07-21 23:18 UTC
Crashes when changing the scale of the colormap (using the "rescale to custom range) when a non-orthogonal slice is in the pipeline. The program crashes immediately upon setting a custom color range. It happened with multiple data sets and the default and grayscale colormaps.

Windows 7, 64-bit, Tomviz 0.5.1
Mac OSX, Tomviz 0.5.1

**Comment by Hovden** [comment] 2015-07-22 01:50
Added this critical bug into 0.6 and pushed less important bug #66 out of 0.6 and into 0.7 release.

**Comment by mathturtle** [comment] 2015-07-22 14:42
I am able to reproduce this and I've tracked down the bug.  It's an assumption being made in ParaView in the colormap editor.  I'll have a patch up to fix it in an hour or two, but since it is a bug in ParaView it may be a day or two before this makes it into TomViz.

**Comment by mathturtle** [comment] 2015-07-22 16:01
ParaView merge request here: https://gitlab.kitware.com/paraview/paraview/merge_requests/245

**Comment by Hovden** [comment] 2015-07-22 16:36
Great!

**Comment by mathturtle** [comment] 2015-07-23 18:15
Building with ParaView newer than commit 275743f9a439ca10cd2b3e29206533c85318b45a fixes this issue.  I have a superbuild patch up to update ParaView, which I'll merge as soon as I've tested OSX and Windows.

**Comment by mathturtle** [comment] 2015-07-23 19:42
@Hovden  I went ahead and updated ParaView in the superbuild.  After the builds catch up, the latest builds should have the fix for this.  Close this when you confirm it is gone.

**Comment by Hovden** [comment] 2015-07-23 20:52
"Rescale to custom range" does not update the histogram colormap. However, if I move the curser of the histogram, it will refresh with the proper colormap.

**Comment by mathturtle** [comment] 2015-07-24 19:47
I can confirm that this histogram update issue happens on MacOS but not on my Linux machine... weird.  However this happens regardless of the non-orthogonal slice being there.  I'm building with the old ParaView now to see if this is a ParaView regression or just a bug somewhere.
cc: @utkarshayachit

**Comment by mathturtle** [comment] 2015-07-24 20:27
This histogram update should be opened as a separate issue.  I can confirm that the update to ParaView did not affect it.  Building against older ParaView gave the same behaviour.  When the colormap is updated via Rescale to Custom Range, the histogram update is not triggered until the user moves the mouse over the histogram.

**Closed** 2015-07-28 16:11 UTC
Labels: bug, under-development
