### ISSUE TITLE
Glitchy junk in histogram

### ISSUE THREAD

**Issue by ElliotPadgett** [OpenChemistry/tomviz#1423] opened 2018-02-20 16:56 UTC
I just downloaded 1.2.1 for Mac to check that my other issues were still present in the latest stable version, and when I open it it looks like this:

![image](https://user-images.githubusercontent.com/12242066/36437259-8024db1e-1634-11e8-932a-0b29af8efd1d.png)

with lots of glitchy junk where the histogram view should be.  Loading a dataset doesn't fix it, it just adds more junk:

![image](https://user-images.githubusercontent.com/12242066/36437270-86e32eb0-1634-11e8-8134-6edf41ba5280.png)

Rescaling the window doesn't fix it, just makes the junk move.  I remember seeing something like this before, so I don't know if this is a known issue, but it's a bad look for the latest stable release to open like this!

**Comment by cryos** [comment] 2018-02-20 17:00
Can you offer any detail on what version of macOS you are using? We do not see this on macOS, there were some driver issues in older OSes, and Apple unfortunately ties graphics driver updates to OS updates.

**Comment by cryos** [comment] 2018-02-20 18:10
This is a duplicate of #1254, 10.10 had some real issues with rendering. I followed up with Mike, and updating his OS fixed it. It only seems to affect certain hardware combinations, maybe we should declare 10.10 as unsupported, it is pretty old at this stage.

**Comment by cryos** [comment] 2018-02-20 18:13
Looking at the Wikipedia page, "Unsupported as of September 2017, iTunes support to end in August 2018, similar to Mavericks." So it looks unlikely that the driver issues will be resolved.

**Comment by cryos** [comment] 2018-02-22 17:01
Closing, as far as I can tell this is a driver issue, and an operating system upgrade has fixed it in every case we are aware of. I will bump our minimum macOS version to 10.11 in the next release as it would appear there are a number of OpenGL issues, and Apple no longer supports this operating system.

**Closed by cryos** 2018-02-22 17:01 UTC
