### ISSUE TITLE
Read raw crashes if data extents are left at defaults.

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#135] opened 2015-07-28 15:25 UTC
When attempting to load a raw file using default data specification (obviously incorrect) the entire tomviz crashes.

Crash tested on Linux.

**Comment by mathturtle** [comment] 2015-07-28 15:30
Confirmed.  Because the default extents are 0 to 0 in all dimensions.  It fails a vtk assertion that min < max.

**Comment by Hovden** [comment] 2015-07-28 15:32
Change the defaults from "0 to 0" to "0 to 1" in all dimensions. Might be a quick Paraview fix. @utkarshayachit

**Comment by utkarshayachit** [comment] 2015-07-28 15:34
@mathturtle Can we change the assertion to be an error message, rather than an assert? We could change the default too, but seems to me incorrect inputs should not cause a segfault.

**Comment by mathturtle** [comment] 2015-07-28 16:01
Ok, I was slightly wrong in my diagnosis.  The assert is in vtkSMTransferFunctionProxy, when it goes to rescale the data to the new range and the max and min of the range are the same. Thinking about it a bit more, extents of 0 to 0 should still give 1 element in the image.  I'll have a ParaView MR soon when I've figured out the best way to fix it.

**Comment by utkarshayachit** [comment] 2015-07-28 16:11
I think that was fixed in ParaView  [recently](https://gitlab.kitware.com/paraview/paraview/commit/a9cb582ed5647f4b34cefc907013a14677924b5c). Can you confirm that this is happening despite this commit?

**Comment by mathturtle** [comment] 2015-07-28 16:49
Yes, I'm using paraview master.

**Comment by mathturtle** [comment] 2015-07-28 17:50
This is something in ParaView's vtkSMTransferFunctionProxy about line 300ish in the function vtkSMTransferFunctionProxy::RescaleTransferFunction.

**Comment by utkarshayachit** [comment] 2015-07-29 15:21
Fixed by https://gitlab.kitware.com/paraview/paraview/merge_requests/255

**Comment by mathturtle** [comment] 2015-07-29 18:01
If we can get the ParaView branch merged this will be fixed by the ParaView update that has to be done anyway.  I'm waiting on another branch in ParaView, so I may as well wait on this one too.  Adding it to 0.6.

**Closed** 2015-08-02 23:35 UTC
Labels: bug, under-development
