### ISSUE TITLE
Setting current image = 0 crashes in manuel alignment tomviz

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#1130] opened 2017-03-28 19:56 UTC
1. Open manual alignment tool
2. Setting current image to 0 
Tomviz crashes

[Windows]

**Comment by mathturtle** [comment] 2017-03-28 20:08
I'll look at this.

**Comment by mathturtle** [comment] 2017-03-28 20:18
Hmmm, doesn't happen here on Linux.  I'll try on Windows.

**Comment by mathturtle** [comment] 2017-03-28 20:46
It doesn't happen on Windows either.  I'm not sure what you did but I can't reproduce it.

**Comment by cquammen** [comment] 2017-03-28 20:57
Could not reproduce on macOS either. @Hovden If you could specify step-by-step directions you took that led to the crash (data set loaded, menu items selected, etc.)? That might get us closer to reproducing the issue.

**Comment by cryos** [comment] 2017-03-29 14:50
I also failed to reproduce this, and looking at the code I don't see an obvious bad path.

**Comment by yijiang1** [comment] 2017-03-29 14:56
I can't reproduce this either.

**Comment by Hovden** [comment] 2017-03-29 15:03
Ok. We were using a dataset from nat.data paper. I guess just close this until I can provide more details.

**Comment by cryos** [comment] 2017-05-31 17:12
Closing for now, please reopen if you have a recipe to reproduce

**Closed by cryos** 2017-05-31 17:12 UTC
Labels: bug
