### ISSUE TITLE
Properties Panel repeats and is glitchy

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#400] opened 2016-05-11 17:33 UTC
Within the last couple merged pull requests the data properties menu has gotten really long. It repeats information. It also is glitchier than previous (I know that is vague).
<img width="306" alt="screen shot 2016-05-11 at 1 33 03 pm" src="https://cloud.githubusercontent.com/assets/6197997/15190256/e9d24e42-177c-11e6-997e-0105b4d103ae.png">

**Comment by Hovden** [comment] 2016-05-11 17:36
Version OSX 0.7.2-143-g7d9b1b2

**Comment by mathturtle** [comment] 2016-05-11 17:45
Confirmed.  Doesn't happen on Linux (with my local build), but the OSX binaries reproduce this for me.

**Comment by cryos** [comment] 2016-05-11 18:08
PR #399 was intended to address that, it was a Mac OS X specific bug. This was merged this morning, the -140- binaries from yesterday also exhibited that problem. I can confirm it is no better with that change on bigmac either, @utkarshayachit any other ideas on that one?

**Comment by mathturtle** [comment] 2016-05-11 18:11
I'm going to try removing the QVTKWidgets from the properties panel temporarily and see if that fixes it.  If so it is a problem with QVTKWidget and Qt5... @utkarshayachit suggested it as a first step in debugging this.

**Comment by cryos** [comment] 2016-05-11 18:19
Testing on bigmac, I see that -138- has a working panel, https://open.cdash.org/viewFiles.php?buildid=4354229 is the link, does that work for you too @Hovden? Just trying to at least narrow down what changes may have triggered this.

**Comment by Hovden** [comment] 2016-05-11 18:27
Properties panel in build -138- is working as was normal (only minor glitch in "Mapping Data" appearance)
Properties panel in build -140- and -143- is not working (repeats information and glitchy)

**Comment by cryos** [comment] 2016-05-11 19:00
Confirmed here, and with @mathturtle. I am going to try moving the ParaView SHA back and see if that confirms that it is isolated to recent changes in ParaView (that appears to be the case from what I can tell).

**Comment by mathturtle** [comment] 2016-05-11 20:39
Did VTK change between the ParaView updates?  More specifically QVTKWidget?  I just did a build with the QVTKWidget removed from the pqTransferFunctionEditor and it gets rid of the bug.  (Of course it doesn't really show anything useful there anymore, but we have the histogram colormap editor now...)

If anyone is interested, here is the ParaView patch I used to remove the QVTKWidget:
[remove-qvtkwidget.patch.txt](https://github.com/OpenChemistry/tomviz/files/260202/remove-qvtkwidget.patch.txt)

**Comment by cryos** [comment] 2016-05-11 22:32
I am sure the VTK submodule did change, I have confirmed the new build with the reverted ParaView SHA looks better on Mac OS X. It is the more recent of the builds today. Not marking this as fixed, but it may be better for us to stay on an older SHA for this release.

**Comment by mathturtle** [comment] 2016-05-12 15:33
@utkarshayachit's QT_WS_*/QT_OS_* change to VTK/ParaView doesn't affect this bug.  I figured I'd try it (or revert it if it was already in) since it is the only recent change to QVTKWidget that I know of.

**Comment by cryos** [comment] 2016-05-12 15:48
I think we are OK for now, and don't see any point in putting more time into investigating at this stage. Before the 0.9 release I would like to replace that dialog so as to reduce the duplication of functionality, and improve the consistency of our user interface - I am not sure it is worth investing more effort looking into this for us.

**Closed by cryos** 2016-05-12 15:48 UTC
Labels: bug
