### ISSUE TITLE
Resetting Color Preset Removes all the Defaults

### ISSUE THREAD

**Issue by jtschwar** [OpenChemistry/tomviz#1902] opened 2019-07-16 19:17 UTC
**Describe the bug**

If you click 'Reset to Defaults' in the Color Presets menu all the color maps disappear. 

**To Reproduce**
1. Go to 'Color Presets'
2. Click on 'Reset to Defaults' and Click 'Ok'

`QIODevice::read (QFile, "/Users/hovdengroup/tomviz-build/bin/tomviz.app/Contents/MacOS/../share/tomviz/defaultcolormaps.json"): device not open`

**Screenshots**

Before:
![image](https://user-images.githubusercontent.com/32110921/61323049-0715f000-a7dd-11e9-833a-c33ab0444ead.png)

After:
![image](https://user-images.githubusercontent.com/32110921/61322903-b7cfbf80-a7dc-11e9-8de8-9dcddec63ba3.png)

**Desktop (please complete the following information):**
 - Operating system:  macOS 10.11
 - Tomviz version: [e.g. 1.6.0-151]

**Hardware (please complete the following information):**
 - Device: [e.g. iMac and Macbook Pro]

**Comment by cjh1** [comment] 2019-07-17 14:15
I am pretty sure this is a packaging issue.

**Comment by jtschwar** [comment] 2019-07-17 14:20
I see, you're right. It's not an issue with the nightly build, just my local.

**Comment by cjh1** [comment] 2019-07-17 14:47
@jtschwar Looks like in the build environment it can't find `defaultcolormaps.json`. Can you do the following. cd into the directory containing the tomviz executable in your build tree and run `ls ../../../../share/tomviz/defaultcolormaps.json`. And then move one directory up and run `find . -name defaultcolormaps.json`. We are trying to see where your `defaultcolormaps.json` file is. Thanks

**Comment by jtschwar** [comment] 2019-07-17 15:37
@cjh1 
These were the outputs I had when I ran all of that (starting from my build directory):

`hlab:tomviz-build hovdengroup$ cd bin/tomviz.app/contents/macos/
hlab:macos hovdengroup$ ls
tomviz
hlab:macos hovdengroup$ ls ../../../../share/tomviz/defaultcolormaps.json
../../../../share/tomviz/defaultcolormaps.json
hlab:macos hovdengroup$ cd ..
hlab:contents hovdengroup$ find . -name defaultcolormaps.json
hlab:contents hovdengroup$ `

I checked and it looks like `defaultcolormaps.json` is in `tomviz-build/share/tomviz` directory

**Comment by cjh1** [comment] 2019-07-17 15:50
@jtschwar Thank, that was very helpful, we can see what the problem is and will push a fix.

**Comment by jtschwar** [comment] 2019-07-17 15:53
@cjh1 Cool, glad to help!

**Comment by cjh1** [comment] 2019-07-17 19:52
This should be fixed by #1905. If you get a chance please try it out.

**Comment by jtschwar** [comment] 2019-07-17 20:51
@cjh1 yep, it works! Thanks!

**Closed** 2019-07-17 20:51 UTC
