### ISSUE TITLE
Double click state file fails to open properly

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/tomviz#1707] opened 2018-09-13 23:23 UTC
Windows 10, tomviz 1.4.0

If you save a state file then the tvsm can be double clicked to be directly opened in a fresh tomviz application. When tomviz loads up it throws the following long error message. The pipeline is empty. I can then use tomviz normally.
```
Traceback (most recent call last):
  File "C:/Program Files/tomviz/bin\Lib/site-packages\vtkmodules\vtkCommonKit.py", line 5, in <module>
    from .vtkCommonKitPython import *
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\tomviz\lib\tomviz\site-packages\tomviz\io\_internal.py", line 31, in list_python_readers
    m = importer.find_module(name).load_module(name)
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Program Files\tomviz\lib\tomviz\site-packages\tomviz\io\formats\matlab.py", line 23, in <module>
    import tomviz.utils
  File "C:\Program Files\tomviz\lib\tomviz\site-packages\tomviz\utils.py", line 23, in <module>
    import vtk.numpy_interface.dataset_adapter as dsa
  File "C:/Program Files/tomviz/bin\Lib/site-packages\vtk.py", line 32, in <module>
    all_spec.loader.exec_module(all_m)
  File "C:/Program Files/tomviz/bin\Lib/site-packages\vtkmodules\all.py", line 7, in <module>
    from .vtkCommonKit import *
  File "C:/Program Files/tomviz/bin\Lib/site-packages\vtkmodules\vtkCommonKit.py", line 9, in <module>
    from vtkCommonKitPython import *
ModuleNotFoundError: No module named 'vtkCommonKitPython'
"Error calling list_python_readers."
```
This occured for a very simple state file in which I loaded the example reconstruction and rotated it slightly and then saved the state file.

If I load the state file from File --> Load state then everything works properly and there are no error messages shown at all (I cleared the messages window).

**Comment by ercius** [comment] 2018-09-13 23:36
Opening tomviz by loading a tvsm file also caused  issues with custom transforms. I only add it here in case it helps with tracing the problem. If I close tomviz, open the app cleanly and then load the state file then everything is ok. I get errors like the following:
```
An error occurred trying to load an operator from 'C:/Users/Peter\.tomviz\autoAlign_realFFT.py':
Traceback (most recent call last):
  File "C:/Program Files/tomviz/bin\Lib/site-packages\vtkmodules\vtkCommonKit.py", line 5, in <module>
    from .vtkCommonKitPython import *
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\tomviz\lib\tomviz\site-packages\tomviz\_internal.py", line 129, in _operator_description
    module = _load_module(operator_dir, filename)
  File "C:\Program Files\tomviz\lib\tomviz\site-packages\tomviz\_internal.py", line 109, in _load_module
    module = imp.load_module(module_name, fp, pathname, description)
  File "C:\Program Files\tomviz\bin\lib\imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "C:\Program Files\tomviz\bin\lib\imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:/Users/Peter\.tomviz\autoAlign_realFFT.py", line 1, in <module>
    from tomviz import utils
  File "C:\Program Files\tomviz\lib\tomviz\site-packages\tomviz\utils.py", line 23, in <module>
    import vtk.numpy_interface.dataset_adapter as dsa
  File "C:/Program Files/tomviz/bin\Lib/site-packages\vtk.py", line 32, in <module>
    all_spec.loader.exec_module(all_m)
  File "C:/Program Files/tomviz/bin\Lib/site-packages\vtkmodules\all.py", line 7, in <module>
    from .vtkCommonKit import *
  File "C:/Program Files/tomviz/bin\Lib/site-packages\vtkmodules\vtkCommonKit.py", line 9, in <module>
    from vtkCommonKitPython import *
ModuleNotFoundError: No module named 'vtkCommonKitPython'

Traceback (most recent call last):
  File "C:/Program Files/tomviz/bin\Lib/site-packages\vtkmodules\vtkCommonKit.py", line 5, in <module>
    from .vtkCommonKitPython import *
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by cryos** [comment] 2018-09-20 16:13
This is not currently supported, we would need to look at adding support for opening a state file, and associating state files with the Tomviz binary. I think it is a reasonable request but not something we currently support, and we would need to add some logic to the binary. We should pick apart what would need to be added.

**Comment by ercius** [comment] 2018-09-20 20:27
Do you know if tomviz automatically adds tvsm file associations? If so then this should be removed until the feature is added. Maybe I added this manually after install to my Windows system.

**Comment by cryos** [comment] 2018-09-21 17:00
Not in my testing, and I am not aware of an attempt to do that. If you search for a file, and find Tomviz then it is remembered on the system. I think file association is something we should look at adding, but just wanted to be clear that it wasn't a feature we have yet.

**Comment by psavery** [comment] 2019-03-12 17:02
I added a file association of .tvsm files to tomviz on Ubuntu 18.04, and it actually works as expected. I'll try Windows later when I get access to a Windows machine.

**Comment by psavery** [comment] 2019-03-14 14:31
I installed the latest version of tomviz on Windows, and I was able to reproduce this issue.

In my case, the tomviz installer did not associate .tvsm files automatically. I had to right click the .tvsm file and choose `Open With` to get it to start associating the files with tomviz.

Anyways, I tried printing the current working directory (`os.getcwd()`) in that python file. It looks like, when tomviz is opened normally (via a shortcut, the start menu, or directly opening the binary), the CWD is always the tomviz bin directory. But if you open up tomviz via a state file association on windows, the CWD is the directory of the state file instead. That may be related to the python import issues, and we may be able to fix it by ensuring that the runtime/working directory is the tomviz bin.

**Comment by psavery** [comment] 2019-05-10 21:10
Strangely enough, I tried this again on the latest Windows binary (Tomviz-1.6.0-73-g60b1e8bc) on my personal laptop, and it seemed to work fine. Perhaps upgrading ParaView fixed this issue (I know they moved their libraries to be in `lib` or `lib64`, that might have something to do with it).

**Comment by cryos** [comment] 2019-07-22 09:28
I think this is now fixed, let's reopen if that doesn't hold true on all platforms.

**Closed by cryos** 2019-07-22 09:28 UTC
Labels: enhancement
