### ISSUE TITLE
Crashes when deleting data / All datasets deleted when deleting top dataset

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#572] opened 2016-08-29 20:57 UTC
Crashes:
1) open two datasets
2) delete the second dataset from pipeline
3) crashes
Deletes all data
1) open two datasets
2) delete the top dataset from pipeline
3) both datasets deleted

Tested on OSX

**Comment by cquammen** [comment] 2016-08-31 14:30
Confirmed crashing when deleting data sets, but with a different testing sequence:

1) Open two datasets
2) Delete first
3) Delete second. Crash.

Confirmed deletion of all data sets using the "Delete" key. Cannot reproduce by deleting with "Delete" option in context menu with right-clicking the data source in the pipeline.

**Comment by cquammen** [comment] 2016-08-31 14:32
By the way, catching crash in debugger doesn't reveal anything obvious. Whoever modifies the `PipelineModel` class to support child data sets should look at this, too.

**Comment by cquammen** [comment] 2016-09-02 17:10
This *seems* to be resolved in the latest master. Please report if you continue to have problems.

**Comment by Hovden** [comment] 2016-09-20 21:05
Only partially fixed. No longer crashes, but still deletes all data:
1) open two datasets
2) delete the top dataset from pipeline
3) both datasets deleted

**Comment by cryos** [comment] 2016-10-18 18:27
I do not see this with master, just following up on old bugs. Is this behavior still an issue for you @Hovden? I tried deleting it both from the top, and from the bottom, using the delete key and the context menu.

**Comment by Hovden** [comment] 2016-10-18 18:44
Yeah. Open two sample datasets. Delete a viz module in the top dataset.

I'm finding several bugs in the pipeline (with two datasets try scrolling down by pressing the down arrow key. You'll find it repeats.) I will create a bug list.

**Comment by yijiang1** [comment] 2016-10-18 18:56
On dashboard, the latest binary's version number is 
<img width="313" alt="screen shot 2016-10-18 at 2 52 26 pm" src="https://cloud.githubusercontent.com/assets/13088588/19491899/a42e40a0-9542-11e6-80bb-03d5e81d4763.png">

My local build's version number is
<img width="209" alt="screen shot 2016-10-18 at 2 53 52 pm" src="https://cloud.githubusercontent.com/assets/13088588/19491914/b5d3816c-9542-11e6-9262-0ee2f1572ded.png">

Are they the same version?

**Comment by cryos** [comment] 2016-10-18 18:56
I see the repeat, I can take a look at it. Not able to reproduce the deletion of all data sets here though. I was going to take a look through the code and see if I can spot anything.

**Comment by cryos** [comment] 2016-10-18 18:57
They are not the same version, the -373- and -365- indicate that they see 373 and 365 commits since 0.9.1 respectively. The letters/numbers after are a short version of the SHA - it is the output of the 'git describe' command.

**Comment by yijiang1** [comment] 2016-10-18 18:58
I see. 

> Yeah. Open two sample datasets. Delete a viz module in the top dataset.

This bug is in the binary version (-373-). My local build ( -365-) works fine.

**Comment by cryos** [comment] 2016-10-18 19:00
I am using -373- and not seeing the issue, but on Linux. I will take a look at the packages, maybe there is something different about the binaries. Is this Windows, Mac, or Linux? I will try Mac first, and see what I can see.

**Comment by yijiang1** [comment] 2016-10-18 19:04
This Mac

**Comment by cryos** [comment] 2016-10-18 19:06
We have been making a lot of changes to the pipeline, we can spend some time finding bugs that might have been introduced, some may be more difficult to reproduce than others. Confirmed on Mac with the binary package, I will see what I can find.

**Comment by cquammen** [comment] 2016-10-28 02:13
I just tried out Nightly build 438 for Mac. I could not reproduce any of the crashes reported here.

**Comment by cryos** [comment] 2016-10-28 16:12
Yeah, I think this is resolved now.

**Closed by cryos** 2016-10-28 16:12 UTC
Labels: bug
