### ISSUE TITLE
Web export menu issue

### ISSUE THREAD

**Issue by cjh1** [OpenChemistry/tomviz#1171] opened 2017-05-31 15:37 UTC
The exported app doesn't seem the be able to create the menu:

![error](https://cloud.githubusercontent.com/assets/1031053/26640332/6eeedb20-45f5-11e7-9e12-4db814cf041a.png)
![error2](https://cloud.githubusercontent.com/assets/1031053/26640337/733510dc-45f5-11e7-8f65-73b01e1e30cc.png)

**Comment by cjh1** [comment] 2017-05-31 15:37
@jourdain This is with 5.4 rc 3

**Comment by jourdain** [comment] 2017-05-31 15:40
The issue is in tomviz-web but I had a branch a while back to update it after the release.
I don't know if my PR has been merged or not.

**Comment by cryos** [comment] 2017-05-31 17:42
This seems to be fixed now I merged the branch @jourdain mentioned.

**Closed by cryos** 2017-05-31 17:42 UTC

**Comment by jourdain** [comment] 2017-05-31 18:31
Cool, glad to hear that is back working.

**Comment by cryos** [comment] 2017-05-31 18:36
Yeah, I will do some more testing, but things look pretty good in my local testing, especially with the range list fix for the volumes too. Hoping to get a 1.0.1 out soon, so pushing on fixes.
