### ISSUE TITLE
Resetting segfaults here

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/tomviz#2096] opened 2020-04-08 16:50 UTC
If I use the interactive Python to build a small pipeline, and then reset I get a segfault.
```
Loguru caught a signal: SIGSEGV
Stack trace:
21      0x55b3b024efae _start + 46
20      0x7f4704083023 __libc_start_main + 243
19      0x55b3b024ec0b main + 907
18      0x7f47047fd066 QCoreApplication::exec() + 150
17      0x7f47047f505c QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 300
16      0x7f470484e890 QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 96
15      0x7f47019c4871 g_main_context_iteration + 49
14      0x7f47019c4831 /usr/lib/libglib-2.0.so.0(+0x6d831) [0x7f47019c4831]
13      0x7f47019c29be g_main_context_dispatch + 638
12      0x7f470484f244 /usr/lib/libQt5Core.so.5(+0x2fe244) [0x7f470484f244]
11      0x7f47047f8d56 QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 342
10      0x7f47047f64f2 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 386
9       0x7f4709e31829 QApplication::notify(QObject*, QEvent*) + 825
8       0x7f4709e28352 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 130
7       0x7f4704823870 QObject::event(QEvent*) + 80
6       0x7f470b16af89 tomviz::ModuleSlice::~ModuleSlice() + 9
5       0x7f470b16ae59 tomviz::ModuleSlice::~ModuleSlice() + 393
4       0x7f4704fbaaae vtkSmartPointerBase::~vtkSmartPointerBase() + 30
3       0x7f470b115e39 vtkNonOrthoImagePlaneWidget::~vtkNonOrthoImagePlaneWidget() + 9
2       0x7f470b115c32 vtkNonOrthoImagePlaneWidget::~vtkNonOrthoImagePlaneWidget() + 34
1       0x7f470513b129 vtkObject::RemoveObserver(vtkCommand*) + 9
0       0x7f4704e46800 /usr/lib/libpthread.so.0(+0x14800) [0x7f4704e46800]
(  83.079s) [paraview        ]                       :0     FATL| Signal: SIGSEGV
Segmentation fault (core dumped)
```
This is on the branch for pulling Python apart, I haven't double checked master yet but wanted to record this so it wasn't missed. It doesn't look related to that branch.

**Comment by cryos** [comment] 2020-04-08 16:51
It actually crashes without running interactive Python, just load data and reset.

**Comment by alesgenova** [comment] 2020-04-08 17:01
It looks like a duplicate of #2094

**Closed** 2020-04-08 17:35 UTC
Labels: bug
