### ISSUE TITLE
"Show legend as cube" menu item crashes tomviz

### ISSUE THREAD

**Issue by ElliotPadgett** [OpenChemistry/tomviz#1146] opened 2017-03-29 23:26 UTC
I don't know what this thing is supposed to do, but when I click it the program crashes.

**Comment by yijiang1** [comment] 2017-03-30 03:21
I don't have see this bug on Windows 10. Maybe it only crashes on Mac.

**Comment by Hovden** [comment] 2017-03-30 03:49
It works ok on the osx 1.0 release I have.

**Comment by ercius** [comment] 2017-03-30 04:15
This crashed for me on Windows 10 after playing with an RC1 install
yesterday. However, with a fresh tomviz instance it worked. So, it's not a
trivial thing to reproduce.

**Comment by ElliotPadgett** [comment] 2017-03-30 20:53
Ok, let me check again and see if I can reproduce the conditions.

**Comment by cryos** [comment] 2017-04-02 23:45
I don't see a crash, but do see some issues where it doesn't always render. I will see if I can get to the bottom of it.

**Comment by Hovden** [comment] 2017-06-20 21:06
Crashes on my OSX (10.12.5)

**Comment by cquammen** [comment] 2017-11-08 22:10
I couldn't reproduce on macOS 10.11 or Ubuntu 16.04 on a recent master (33a4b94234040a7558415d07319be77a0ccdd8b2).

**Comment by Hovden** [comment] 2018-03-01 19:05
No longer crashes. However, a check does not appear on the menu "show legend as cube". Add check and close this issue.

**Closed** 2018-03-02 20:50 UTC
Labels: bug, in progress
