### ISSUE TITLE
Deleting top dataset deletes entire pipeline.

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#654] opened 2016-10-05 15:11 UTC
Deleting top dataset deletes entire pipeline (bug identified on OSX).

1) Load 2 datasets.
2) Delete the one at the top of the pipeline.

**Comment by yijiang1** [comment] 2016-10-14 02:44
Interestingly, my local build works fine. The bug still exits on latest binary version.

**Comment by cryos** [comment] 2016-10-19 17:40
We have updated the ParaView SHA, and the ITK binaries, which will trigger a clean build of Tomviz along with all dependencies. I will test the binaries once they are ready, looking into several pipeline issues right now (but unable to reproduce this one in a build tree - I can try to the build on bigmac if it still happens there after the clean builds).

**Comment by cryos** [comment] 2016-10-19 19:48
Getting closer, need to head out, but I see the cause of the issue now. It is quite odd, and not what I thought at first. This may turn out to be affecting a few of the keyboard related pipeline view interactions.

**Comment by yijiang1** [comment] 2016-10-24 14:15
This is fixed on latest binary (-403-).

**Closed** 2016-10-25 14:52 UTC
Labels: bug, in progress
