### ISSUE TITLE
Cannot import state in python console

### ISSUE THREAD

**Issue by SBW90** [OpenChemistry/tomviz#2051] opened 2020-02-26 23:20 UTC
**Describe the bug**
Cannot import modules from tomviz.  Trying to to reproduce code from the [documents](https://tomviz.readthedocs.io/en/latest/interactive/).

I get the error:

```
from tomviz import state
Traceback (most recent call last):
  File "<console>", line 1, in <module>
ImportError: cannot import name 'state' from 'tomviz' (C:\Program Files\tomviz\lib\tomviz\site-packages\tomviz\__init__.py)
````

**To Reproduce**
View -> Python Console
In python console:
`from tomviz import state' 

**Expected behavior**
should be able to use the state.load function to load state files.

**Screenshots**

**Desktop (please complete the following information):**
 - Operating system: , Ubuntu gnome 16.04.6 LTS & Windows 10
 - Tomviz version: 1.7 & 1.8

**Hardware (please complete the following information):**
 - Device: Hp desktop i7, 16gb ram & lenovo t470s i7 20gb ram
 - Graphics card: none

**Additional context**
I can import tomviz and get access to tomviz.__doc__ etc.
```
sys,path
['C:\\Program Files\\tomviz\\lib\\itk\\site-packages', 'C:\\Program Files\\tomviz\\lib\\tomviz\\site-packages', 'C:/Program Files/tomviz\\bin/Lib/site-packages', 'C:\\Program Files\\tomviz\\bin\\python37.zip', 'C:\\Program Files\\tomviz\\bin\\DLLs', 'C:\\Program Files\\tomviz\\bin\\lib', 'C:\\Program Files\\tomviz\\bin', 'C:\\Users\\Alex\\AppData\\Roaming\\Python\\Python37\\site-packages', 'C:\\Program Files\\tomviz\\bin\\lib\\site-packages']
```

**Comment by psavery** [comment] 2020-02-27 00:19
I think @cjh1 can confirm, but if I had to guess, I think it's because the [example from the docs](https://tomviz.readthedocs.io/en/latest/interactive/) isn't a part of a Tomviz release yet. It's only available on the master branch, but will be available in the next release.

**Comment by cjh1** [comment] 2020-02-27 14:25
@SBW90 @psavery Yes, this functionality is not currently in a release, its only in master. You can also download a nightly from [here](https://tomviz.org/downloads/).

**Comment by SBW90** [comment] 2020-02-27 19:59
@cjh1 @psavery  thanks for the fast replies. I tried installing the nightly version and i get this error when launching the python console and when trying to import `state`:

```
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
>>> from tomviz import state
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Program Files\tomviz\lib\tomviz\site-packages\tomviz\state\__init__.py", line 4, in <module>
    from ._schemata import (
  File "C:\Program Files\tomviz\lib\tomviz\site-packages\tomviz\state\_schemata.py", line 4, in <module>
    from marshmallow import (
ModuleNotFoundError: No module named 'marshmallow'
```
I'm not sure how to install `marshmallow`. I tried `pip install marshmallow` in cmd, which successfully installed, but I still get the same error in tomviz after reopening, I guess this is using a different version of python? 

I tried using 'sys' and 'subprocesses' to use `pip` from within tomoviz python console but that didn't work either.  

Any suggestions?

**Comment by cjh1** [comment] 2020-02-27 20:07
@SBW90 Looks like marshmallow is not being package in the the nightly, we will take a look at it.

**Comment by cjh1** [comment] 2020-02-28 21:02
This latest Windows build now includes marshmallow, the Windows installer can be found here: https://open.cdash.org/upload/7d23f63e183b41775b8615f0bf65cc63963b6fdc/Tomviz-1.8.0-107-g67c836ac.msi, I tested the Linux version and things looked good.

**Comment by SBW90** [comment] 2020-03-02 20:55
Looks like its working for me as well, thanks for all your help and speedy replies.

**Comment by cryos** [comment] 2020-03-02 22:07
Glad you were able to get it working, and thanks for reporting the issue. I will close this for now, please reopen if you encounter further issues. This functionality will be in the next release (1.9.0).

**Closed by cryos** 2020-03-02 22:07 UTC

**Comment by SBW90** [comment] 2020-03-04 23:18
Not sure if this should be a different issue or continuation here. Happy to open an new issue if that's better.

I started poking around it a bit more and it looks like the `tomviz.operators` functions aren't working.
I tried an example from the [documentation](https://tomviz.readthedocs.io/en/latest/interactive/):
```from tomviz.operators import InvertData
Traceback (most recent call last):
  File "<console>", line 1, in <module>
ImportError: cannot import name 'InvertData' from 'tomviz.operators' (C:\Program Files\tomviz\lib\tomviz\site-packages\tomviz\operators.py)
```
I looked at  `~/operators.py`  and as far as I can tell there aren't any functions which would operate on the data.

**Comment by cjh1** [comment] 2020-03-05 13:09
@SBW90 Reopening the issue is fine, thanks for reporting it. We will take a look. It looks like its something related to packaging as a built from source version is working as expected.

**Comment by cryos** [comment] 2020-03-05 16:00
That is odd - I used the Linux package to demonstrate this capability on a Linux machine. It is very new as a feature, and so we really appreciate people testing it out and giving us feedback. Hopefully we can get the packaging issues figured out as I really want to feature this in our next release!

**Comment by cjh1** [comment] 2020-03-05 21:06
@SBW90 The latest package is now working on Linux. There is a problem with importing pyffw but that is a separate issue.
