### ISSUE TITLE
Manual Alignment Crashes on Third Use

### ISSUE THREAD

**Issue by Hovden** [OpenChemistry/tomviz#1133] opened 2017-03-28 20:27 UTC
1. Load the Manual Alignment tool.
2. Click OK or Apply.
3. Reload the same manual alignment by double clicking in pipeline. Click OK or apply.
4. Repeat once more and it crashes.
[OSX and Windows]

Most tomography users will adjust the manual alignment tool many times. So this is a more significant bug for tomography.

**Comment by mathturtle** [comment] 2017-03-28 20:49
I can reproduce this one.  Looking at it now.

**Comment by mathturtle** [comment] 2017-03-28 21:26
So this is something to do with our caching of previously used midpoint steps...  I can disable the caching as a quick solution, but nothing is jumping out at me as the problem.  Any ideas @cryos @cjh1?  This should probably be a 1.0 blocker...

Code (see DataSource.cxx line 853 or so)
```c++
vtkSmartPointer<vtkImageData> cached = cache[pointInPipeline]; // map of operator to vtkWeakPointer<vtkImageData>
if (cached) {
  // use it, but it crashes here
}
```

**Comment by cryos** [comment] 2017-03-28 22:36
I could reproduce, and it looks like something isn't right in the caching code as you suggested. replacing cached with false, and bypassing that code resulted in no crashes here. I would rather rerun the pipeline than risk crashing, so that would be reasonable to do. I can try and take a better look at the code later/in the morning.

**Comment by cryos** [comment] 2017-03-28 23:16
There should be some updated binaries shortly that contain this workaround for testing, I just merged a patch disabling the caching for now.

**Comment by cryos** [comment] 2017-03-29 14:11
I am going to mark this as resolved for now, the caching was added as an optimization for C++ operators that had custom GUI and needed to know about the previous step.

**Closed by cryos** 2017-03-29 14:11 UTC
Labels: blocker, bug
